export const locationItems = [
  { location: "Edifício Principal", parent: "Complexo Arquitetônico do Senado Federal", code: "EDP-ANX-000", visiting: "sim", area: "1200" },
  { location: "Gabinete do Senador José Serra", parent: "Edifício Anexo I", code: "GBN-ANX-025", visiting: "não", area: "100" },
  { location: "Diretoria da SINFRA", parent: "Bloco 14", code: "DIR-BLC-012", visiting: "não", area: "70" },
  { location: "Edifício Principal", parent: "Complexo Arquitetônico do Senado Federal", code: "EDP-ANX-000", visiting: "sim", area: "1200" },
  { location: "Gabinete do Senador José Serra", parent: "Edifício Anexo I", code: "GBN-ANX-025", visiting: "não", area: "100" },
  { location: "Diretoria da SINFRA", parent: "Bloco 14", code: "DIR-BLC-012", visiting: "não", area: "70" },
  { location: "Edifício Principal", parent: "Complexo Arquitetônico do Senado Federal", code: "EDP-ANX-000", visiting: "sim", area: "1200" },
  { location: "Gabinete do Senador José Serra", parent: "Edifício Anexo I", code: "GBN-ANX-025", visiting: "não", area: "100" },
  { location: "Diretoria da SINFRA", parent: "Bloco 14", code: "DIR-BLC-012", visiting: "não", area: "70" },
  { location: "Edifício Principal", parent: "Complexo Arquitetônico do Senado Federal", code: "EDP-ANX-000", visiting: "sim", area: "1200" },
  { location: "Gabinete do Senador José Serra", parent: "Edifício Anexo I", code: "GBN-ANX-025", visiting: "não", area: "100" },
  { location: "Diretoria da SINFRA", parent: "Bloco 14", code: "DIR-BLC-012", visiting: "não", area: "70" },
  { location: "Edifício Principal", parent: "Complexo Arquitetônico do Senado Federal", code: "EDP-ANX-000", visiting: "sim", area: "1200" },
  { location: "Gabinete do Senador José Serra", parent: "Edifício Anexo I", code: "GBN-ANX-025", visiting: "não", area: "100" },
  { location: "Diretoria da SINFRA", parent: "Bloco 14", code: "DIR-BLC-012", visiting: "não", area: "70" },
  { location: "Edifício Principal", parent: "Complexo Arquitetônico do Senado Federal", code: "EDP-ANX-000", visiting: "sim", area: "1200" },
  { location: "Gabinete do Senador José Serra", parent: "Edifício Anexo I", code: "GBN-ANX-025", visiting: "não", area: "100" },
  { location: "Diretoria da SINFRA", parent: "Bloco 14", code: "DIR-BLC-012", visiting: "não", area: "70" },
  { location: "Edifício Principal", parent: "Complexo Arquitetônico do Senado Federal", code: "EDP-ANX-000", visiting: "sim", area: "1200" },
  { location: "Gabinete do Senador José Serra", parent: "Edifício Anexo I", code: "GBN-ANX-025", visiting: "não", area: "100" },
  { location: "Diretoria da SINFRA", parent: "Bloco 14", code: "DIR-BLC-012", visiting: "não", area: "70" },
  { location: "Edifício Principal", parent: "Complexo Arquitetônico do Senado Federal", code: "EDP-ANX-000", visiting: "sim", area: "1200" },
  { location: "Gabinete do Senador José Serra", parent: "Edifício Anexo I", code: "GBN-ANX-025", visiting: "não", area: "100" },
  { location: "Diretoria da SINFRA", parent: "Bloco 14", code: "DIR-BLC-012", visiting: "não", area: "70" },
  { location: "Edifício Principal", parent: "Complexo Arquitetônico do Senado Federal", code: "EDP-ANX-000", visiting: "sim", area: "1200" },
  { location: "Gabinete do Senador José Serra", parent: "Edifício Anexo I", code: "GBN-ANX-025", visiting: "não", area: "100" },
  { location: "Diretoria da SINFRA", parent: "Bloco 14", code: "DIR-BLC-012", visiting: "não", area: "70" },
  { location: "Edifício Principal", parent: "Complexo Arquitetônico do Senado Federal", code: "EDP-ANX-000", visiting: "sim", area: "1200" },
  { location: "Gabinete do Senador José Serra", parent: "Edifício Anexo I", code: "GBN-ANX-025", visiting: "não", area: "100" },
  { location: "Diretoria da SINFRA", parent: "Bloco 14", code: "DIR-BLC-012", visiting: "não", area: "70" },
  { location: "Edifício Principal", parent: "Complexo Arquitetônico do Senado Federal", code: "EDP-ANX-000", visiting: "sim", area: "1200" },
  { location: "Gabinete do Senador José Serra", parent: "Edifício Anexo I", code: "GBN-ANX-025", visiting: "não", area: "100" },
  { location: "Diretoria da SINFRA", parent: "Bloco 14", code: "DIR-BLC-012", visiting: "não", area: "70" },
  { location: "Edifício Principal", parent: "Complexo Arquitetônico do Senado Federal", code: "EDP-ANX-000", visiting: "sim", area: "1200" },
  { location: "Gabinete do Senador José Serra", parent: "Edifício Anexo I", code: "GBN-ANX-025", visiting: "não", area: "100" },
  { location: "Diretoria da SINFRA", parent: "Bloco 14", code: "DIR-BLC-012", visiting: "não", area: "70" },
  { location: "Edifício Principal", parent: "Complexo Arquitetônico do Senado Federal", code: "EDP-ANX-000", visiting: "sim", area: "1200" },
  { location: "Gabinete do Senador José Serra", parent: "Edifício Anexo I", code: "GBN-ANX-025", visiting: "não", area: "100" },
  { location: "Diretoria da SINFRA", parent: "Bloco 14", code: "DIR-BLC-012", visiting: "não", area: "70" },
  { location: "Edifício Principal", parent: "Complexo Arquitetônico do Senado Federal", code: "EDP-ANX-000", visiting: "sim", area: "1200" },
  { location: "Gabinete do Senador José Serra", parent: "Edifício Anexo I", code: "GBN-ANX-025", visiting: "não", area: "100" },
  { location: "Diretoria da SINFRA", parent: "Bloco 14", code: "DIR-BLC-012", visiting: "não", area: "70" },
  { location: "Edifício Principal", parent: "Complexo Arquitetônico do Senado Federal", code: "EDP-ANX-000", visiting: "sim", area: "1200" },
  { location: "Gabinete do Senador José Serra", parent: "Edifício Anexo I", code: "GBN-ANX-025", visiting: "não", area: "100" },
  { location: "Diretoria da SINFRA", parent: "Bloco 14", code: "DIR-BLC-012", visiting: "não", area: "70" },
  { location: "Edifício Principal", parent: "Complexo Arquitetônico do Senado Federal", code: "EDP-ANX-000", visiting: "sim", area: "1200" },
  { location: "Gabinete do Senador José Serra", parent: "Edifício Anexo I", code: "GBN-ANX-025", visiting: "não", area: "100" },
  { location: "Diretoria da SINFRA", parent: "Bloco 14", code: "DIR-BLC-012", visiting: "não", area: "70" },
  { location: "Edifício Principal", parent: "Complexo Arquitetônico do Senado Federal", code: "EDP-ANX-000", visiting: "sim", area: "1200" },
  { location: "Gabinete do Senador José Serra", parent: "Edifício Anexo I", code: "GBN-ANX-025", visiting: "não", area: "100" },
  { location: "Diretoria da SINFRA", parent: "Bloco 14", code: "DIR-BLC-012", visiting: "não", area: "70" },
  { location: "Edifício Principal", parent: "Complexo Arquitetônico do Senado Federal", code: "EDP-ANX-000", visiting: "sim", area: "1200" },
  { location: "Gabinete do Senador José Serra", parent: "Edifício Anexo I", code: "GBN-ANX-025", visiting: "não", area: "100" },
  { location: "Diretoria da SINFRA", parent: "Bloco 14", code: "DIR-BLC-012", visiting: "não", area: "70" },
  { location: "Edifício Principal", parent: "Complexo Arquitetônico do Senado Federal", code: "EDP-ANX-000", visiting: "sim", area: "1200" },
  { location: "Gabinete do Senador José Serra", parent: "Edifício Anexo I", code: "GBN-ANX-025", visiting: "não", area: "100" },
  { location: "Diretoria da SINFRA", parent: "Bloco 14", code: "DIR-BLC-012", visiting: "não", area: "70" },
  { location: "Edifício Principal", parent: "Complexo Arquitetônico do Senado Federal", code: "EDP-ANX-000", visiting: "sim", area: "1200" },
  { location: "Gabinete do Senador José Serra", parent: "Edifício Anexo I", code: "GBN-ANX-025", visiting: "não", area: "100" },
  { location: "Diretoria da SINFRA", parent: "Bloco 14", code: "DIR-BLC-012", visiting: "não", area: "70" },
  { location: "Edifício Principal", parent: "Complexo Arquitetônico do Senado Federal", code: "EDP-ANX-000", visiting: "sim", area: "1200" },
  { location: "Gabinete do Senador José Serra", parent: "Edifício Anexo I", code: "GBN-ANX-025", visiting: "não", area: "100" },
  { location: "Diretoria da SINFRA", parent: "Bloco 14", code: "DIR-BLC-012", visiting: "não", area: "70" },
  { location: "Edifício Principal", parent: "Complexo Arquitetônico do Senado Federal", code: "EDP-ANX-000", visiting: "sim", area: "1200" },
  { location: "Gabinete do Senador José Serra", parent: "Edifício Anexo I", code: "GBN-ANX-025", visiting: "não", area: "100" },
  { location: "Diretoria da SINFRA", parent: "Bloco 14", code: "DIR-BLC-012", visiting: "não", area: "70" },
  { location: "Edifício Principal", parent: "Complexo Arquitetônico do Senado Federal", code: "EDP-ANX-000", visiting: "sim", area: "1200" },
  { location: "Gabinete do Senador José Serra", parent: "Edifício Anexo I", code: "GBN-ANX-025", visiting: "não", area: "100" },
  { location: "Diretoria da SINFRA", parent: "Bloco 14", code: "DIR-BLC-012", visiting: "não", area: "70" },
  { location: "Edifício Principal", parent: "Complexo Arquitetônico do Senado Federal", code: "EDP-ANX-000", visiting: "sim", area: "1200" },
  { location: "Gabinete do Senador José Serra", parent: "Edifício Anexo I", code: "GBN-ANX-025", visiting: "não", area: "100" },
  { location: "Diretoria da SINFRA", parent: "Bloco 14", code: "DIR-BLC-012", visiting: "não", area: "70" },
  { location: "Edifício Principal", parent: "Complexo Arquitetônico do Senado Federal", code: "EDP-ANX-000", visiting: "sim", area: "1200" },
  { location: "Gabinete do Senador José Serra", parent: "Edifício Anexo I", code: "GBN-ANX-025", visiting: "não", area: "100" },
  { location: "Diretoria da SINFRA", parent: "Bloco 14", code: "DIR-BLC-012", visiting: "não", area: "70" },
  { location: "Edifício Principal", parent: "Complexo Arquitetônico do Senado Federal", code: "EDP-ANX-000", visiting: "sim", area: "1200" },
  { location: "Gabinete do Senador José Serra", parent: "Edifício Anexo I", code: "GBN-ANX-025", visiting: "não", area: "100" },
  { location: "Diretoria da SINFRA", parent: "Bloco 14", code: "DIR-BLC-012", visiting: "não", area: "70" },
  { location: "Edifício Principal", parent: "Complexo Arquitetônico do Senado Federal", code: "EDP-ANX-000", visiting: "sim", area: "1200" },
  { location: "Gabinete do Senador José Serra", parent: "Edifício Anexo I", code: "GBN-ANX-025", visiting: "não", area: "100" },
  { location: "Diretoria da SINFRA", parent: "Bloco 14", code: "DIR-BLC-012", visiting: "não", area: "70" },
  { location: "Edifício Principal", parent: "Complexo Arquitetônico do Senado Federal", code: "EDP-ANX-000", visiting: "sim", area: "1200" },
  { location: "Gabinete do Senador José Serra", parent: "Edifício Anexo I", code: "GBN-ANX-025", visiting: "não", area: "100" },
  { location: "Diretoria da SINFRA", parent: "Bloco 14", code: "DIR-BLC-012", visiting: "não", area: "70" },
  { location: "Edifício Principal", parent: "Complexo Arquitetônico do Senado Federal", code: "EDP-ANX-000", visiting: "sim", area: "1200" },
  { location: "Gabinete do Senador José Serra", parent: "Edifício Anexo I", code: "GBN-ANX-025", visiting: "não", area: "100" },
  { location: "Diretoria da SINFRA", parent: "Bloco 14", code: "DIR-BLC-012", visiting: "não", area: "70" },
  { location: "Edifício Principal", parent: "Complexo Arquitetônico do Senado Federal", code: "EDP-ANX-000", visiting: "sim", area: "1200" },
  { location: "Gabinete do Senador José Serra", parent: "Edifício Anexo I", code: "GBN-ANX-025", visiting: "não", area: "100" },
  { location: "Diretoria da SINFRA", parent: "Bloco 14", code: "DIR-BLC-012", visiting: "não", area: "70" },
  { location: "Edifício Principal", parent: "Complexo Arquitetônico do Senado Federal", code: "EDP-ANX-000", visiting: "sim", area: "1200" },
  { location: "Gabinete do Senador José Serra", parent: "Edifício Anexo I", code: "GBN-ANX-025", visiting: "não", area: "100" },
  { location: "Diretoria da SINFRA", parent: "Bloco 14", code: "DIR-BLC-012", visiting: "não", area: "70" },
  { location: "Edifício Principal", parent: "Complexo Arquitetônico do Senado Federal", code: "EDP-ANX-000", visiting: "sim", area: "1200" },
  { location: "Gabinete do Senador José Serra", parent: "Edifício Anexo I", code: "GBN-ANX-025", visiting: "não", area: "100" },
  { location: "Diretoria da SINFRA", parent: "Bloco 14", code: "DIR-BLC-012", visiting: "não", area: "70" },
  { location: "Edifício Principal", parent: "Complexo Arquitetônico do Senado Federal", code: "EDP-ANX-000", visiting: "sim", area: "1200" },
  { location: "Gabinete do Senador José Serra", parent: "Edifício Anexo I", code: "GBN-ANX-025", visiting: "não", area: "100" },
  { location: "Diretoria da SINFRA", parent: "Bloco 14", code: "DIR-BLC-012", visiting: "não", area: "70" },
  { location: "Edifício Principal", parent: "Complexo Arquitetônico do Senado Federal", code: "EDP-ANX-000", visiting: "sim", area: "1200" },
  { location: "Gabinete do Senador José Serra", parent: "Edifício Anexo I", code: "GBN-ANX-025", visiting: "não", area: "100" },
  { location: "Diretoria da SINFRA", parent: "Bloco 14", code: "DIR-BLC-012", visiting: "não", area: "70" },
  { location: "Edifício Principal", parent: "Complexo Arquitetônico do Senado Federal", code: "EDP-ANX-000", visiting: "sim", area: "1200" },
  { location: "Gabinete do Senador José Serra", parent: "Edifício Anexo I", code: "GBN-ANX-025", visiting: "não", area: "100" },
  { location: "Diretoria da SINFRA", parent: "Bloco 14", code: "DIR-BLC-012", visiting: "não", area: "70" },
  { location: "Edifício Principal", parent: "Complexo Arquitetônico do Senado Federal", code: "EDP-ANX-000", visiting: "sim", area: "1200" },
  { location: "Gabinete do Senador José Serra", parent: "Edifício Anexo I", code: "GBN-ANX-025", visiting: "não", area: "100" },
  { location: "Diretoria da SINFRA", parent: "Bloco 14", code: "DIR-BLC-012", visiting: "não", area: "70" },
  { location: "Edifício Principal", parent: "Complexo Arquitetônico do Senado Federal", code: "EDP-ANX-000", visiting: "sim", area: "1200" },
  { location: "Gabinete do Senador José Serra", parent: "Edifício Anexo I", code: "GBN-ANX-025", visiting: "não", area: "100" },
  { location: "Diretoria da SINFRA", parent: "Bloco 14", code: "DIR-BLC-012", visiting: "não", area: "70" },
  { location: "Edifício Principal", parent: "Complexo Arquitetônico do Senado Federal", code: "EDP-ANX-000", visiting: "sim", area: "1200" },
  { location: "Gabinete do Senador José Serra", parent: "Edifício Anexo I", code: "GBN-ANX-025", visiting: "não", area: "100" },
  { location: "Diretoria da SINFRA", parent: "Bloco 14", code: "DIR-BLC-012", visiting: "não", area: "70" },
  { location: "Edifício Principal", parent: "Complexo Arquitetônico do Senado Federal", code: "EDP-ANX-000", visiting: "sim", area: "1200" },
  { location: "Gabinete do Senador José Serra", parent: "Edifício Anexo I", code: "GBN-ANX-025", visiting: "não", area: "100" },
  { location: "Diretoria da SINFRA", parent: "Bloco 14", code: "DIR-BLC-012", visiting: "não", area: "70" },
  { location: "Edifício Principal", parent: "Complexo Arquitetônico do Senado Federal", code: "EDP-ANX-000", visiting: "sim", area: "1200" },
  { location: "Gabinete do Senador José Serra", parent: "Edifício Anexo I", code: "GBN-ANX-025", visiting: "não", area: "100" },
  { location: "Diretoria da SINFRA", parent: "Bloco 14", code: "DIR-BLC-012", visiting: "não", area: "70" },
  { location: "Edifício Principal", parent: "Complexo Arquitetônico do Senado Federal", code: "EDP-ANX-000", visiting: "sim", area: "1200" },
  { location: "Gabinete do Senador José Serra", parent: "Edifício Anexo I", code: "GBN-ANX-025", visiting: "não", area: "100" },
  { location: "Diretoria da SINFRA", parent: "Bloco 14", code: "DIR-BLC-012", visiting: "não", area: "70" },
  { location: "Edifício Principal", parent: "Complexo Arquitetônico do Senado Federal", code: "EDP-ANX-000", visiting: "sim", area: "1200" },
  { location: "Gabinete do Senador José Serra", parent: "Edifício Anexo I", code: "GBN-ANX-025", visiting: "não", area: "100" },
  { location: "Diretoria da SINFRA", parent: "Bloco 14", code: "DIR-BLC-012", visiting: "não", area: "70" },
  { location: "Edifício Principal", parent: "Complexo Arquitetônico do Senado Federal", code: "EDP-ANX-000", visiting: "sim", area: "1200" },
  { location: "Gabinete do Senador José Serra", parent: "Edifício Anexo I", code: "GBN-ANX-025", visiting: "não", area: "100" },
  { location: "Diretoria da SINFRA", parent: "Bloco 14", code: "DIR-BLC-012", visiting: "não", area: "70" },
  { location: "Edifício Principal", parent: "Complexo Arquitetônico do Senado Federal", code: "EDP-ANX-000", visiting: "sim", area: "1200" },
  { location: "Gabinete do Senador José Serra", parent: "Edifício Anexo I", code: "GBN-ANX-025", visiting: "não", area: "100" },
  { location: "Diretoria da SINFRA", parent: "Bloco 14", code: "DIR-BLC-012", visiting: "não", area: "70" },
  { location: "Edifício Principal", parent: "Complexo Arquitetônico do Senado Federal", code: "EDP-ANX-000", visiting: "sim", area: "1200" },
  { location: "Gabinete do Senador José Serra", parent: "Edifício Anexo I", code: "GBN-ANX-025", visiting: "não", area: "100" },
  { location: "Diretoria da SINFRA", parent: "Bloco 14", code: "DIR-BLC-012", visiting: "não", area: "70" },
];

export const equipmentItems = [
  { id: "ICA-ASD-120", equipment: "Quadro Elétrico", manufacturer: "Tigre", model: "BO823F", category: "Elétrico", maintenance: "CT 12/2019", location: "Edifício Principal" },
  { id: "ACK-SAD-324", equipment: "Ar Condicionado", manufacturer: "Midea", model: "AS4302F", category: "Mecânico", maintenance: "CT 19/2018", location: "Edifício Principal" },
  { id: "SCS-ADF-421", equipment: "Cortina", manufacturer: "Bella Janela", model: "ASD65F", category: "Civil", maintenance: "CT 22/2017", location: "Edifício Principal" },
  { id: "ASC-FJF-523", equipment: "Nobreak", manufacturer: "Engetron", model: "ASD546F", category: "Elétrico", maintenance: "CT 12/2019", location: "Edifício Principal" },
  { id: "SFL-FSD-123", equipment: "Quadro Elétrico", manufacturer: "Tigre", model: "ASD561F", category: "Elétrico", maintenance: "CT 12/2019", location: "Edifício Principal" },
  { id: "OJU-LDJ-098", equipment: "Nobreak", manufacturer: "Engetron", model: "WER654", category: "Elétrico", maintenance: "CT 12/2019", location: "Edifício Principal" },
  { id: "VJF-JFD-301", equipment: "Ar Condicionado", manufacturer: "Carrier", model: "GDF6351", category: "Mecânico", maintenance: "CT 19/2018", location: "Edifício Principal" },
  { id: "FJA-FKF-109", equipment: "Luminária", manufacturer: "Schneider", model: "WREW654", category: "Elétrico", maintenance: "CT 12/2019", location: "Edifício Principal" },
  { id: "OJU-LDJ-098", equipment: "Nobreak", manufacturer: "Engetron", model: "WER654", category: "Elétrico", maintenance: "CT 12/2019", location: "Edifício Principal" },
  { id: "VJF-JFD-301", equipment: "Ar Condicionado", manufacturer: "Carrier", model: "GDF6351", category: "Mecânico", maintenance: "CT 19/2018", location: "Edifício Principal" },
  { id: "FJA-FKF-109", equipment: "Luminária", manufacturer: "Schneider", model: "WREW654", category: "Elétrico", maintenance: "CT 12/2019", location: "Edifício Principal" },
];

export const locationConfig = [
  { name: "location", description: "Localização", style: { width: "200px" }, className: "" },
  { name: "code", description: "Código", style: { width: "80px" }, className: "text-center" },
  { name: "area", description: "Área", style: { width: "50px" }, className: "text-center" },
  { name: "map", description: "Planta", style: { width: "50px" }, className: "text-center" }
];

export const equipmentConfig = [
  { name: "equipment", description: "Equipamento", style: { width: "200px" }, className: "" },
  { name: "manufacturer", description: "Marca", style: { width: "200px" }, className: "text-center" },
  { name: "model", description: "Modelo", style: { width: "150px" }, className: "text-center" },
  { name: "serie", description: "Nº de Série", style: { width: "150px" }, className: "text-center" },
];