# replace default config

# multipass: true
# full: true

plugins:

  # - name
  #
  # or:
  # - name: false
  # - name: true
  #
  # or:
  # - name:
  #     param1: 1
  #     param2: 2

  - inlineStyles
  - removeDoctype
  - removeXMLProcInst
  - removeComments
  - removeMetadata: false
  - removeTitle
  - removeDesc
  - removeUselessDefs
  - removeXMLNS: false
  - removeEditorsNSData
  - removeAttrs
  - removeHiddenElems: false
  - removeEmptyText
  - removeEmptyContainers
  - removeViewBox
  - cleanupEnableBackground
  - minifyStyles
  - convertStyleToAttrs
  - convertColors
  - convertPathData
  - convertTransform
  - removeUnknownsAndDefaults: false
  - removeNonInheritableGroupAttrs: false
  - removeUselessStrokeAndFill
  - removeUnusedNS
  - cleanupIDs: false
  - prefixIds: false
  - cleanupNumericValues
  - cleanupListOfValues: false
  - moveElemsAttrsToGroup
  - moveGroupAttrsToElems
  - collapseGroups
  - removeRasterImages: false
  - mergePaths
  - convertShapeToPath
  - convertEllipseToCircle
  - sortAttrs: false
  - sortDefsChildren
  - removeDimensions: false
  - removeAttrs: false
  - removeEmptyAttrs: false
  - removeAttributesBySelector: false
  - removeElementsByAttr: false
  - addClassesToSVGElement: false
  - removeStyleElement: false
  - removeScriptElement: false
  - addAttributesToSVGElement: false
  - removeOffCanvasPaths: false
  - reusePaths: false

# configure the indent (default 4 spaces) used by `--pretty` here:
#
# @see https://github.com/svg/svgo/blob/master/lib/svgo/js2svg.js#L6 for more config options
#
# js2svg:
#  pretty: true
#  indent: '  '