# FROM (first layer, with the OS for the container)

# LABEL (maintainers)

# Install npm and nodejs

# Copy web server directory contents (from Docker host to the container)

# WORKDIR

# RUN npm install

# EXPOSE port