export default {
  title: 'Nova Ordem de Serviço',
  button: 'Criar Ordem de Serviço',
  inputs: [
    // OBJECT MANDATORY FORMAT:
    // {
    //   autoFocus: false,
    //   id: 'id',
    //   label: 'label',
    //   multiple: false,
    //   name: 'name',
    //   options: [],
    //   placeholder: 'placeholder',
    //   required: false,
    //   type: 'type',
    // },
    {
      autoFocus: true,
      id: 'title',
      label: 'Título',
      multiple: false,
      name: 'title',
      options: [],
      placeholder: 'Título',
      required: true,
      type: 'text',
    },
    {
      autoFocus: false,
      id: 'description',
      label: 'Descrição',
      multiple: false,
      name: 'description',
      options: [],
      placeholder: 'Descrição',
      required: true,
      type: 'textarea',
    },
    {
      autoFocus: false,
      id: 'assets',
      label: 'Ativos',
      multiple: true,
      name: 'assets',
      options: [],
      placeholder: 'assets',
      required: true,
      type: 'select',
    },
    {
      autoFocus: false,
      id: 'status',
      label: 'Status',
      multiple: false,
      name: 'status',
      options: [],
      placeholder: 'Selecione o status',
      required: true,
      type: 'select',
    },
    {
      autoFocus: false,
      id: 'priority',
      label: 'Prioridade',
      multiple: false,
      name: 'priority',
      options: [],
      placeholder: 'Selecione a prioridade',
      required: true,
      type: 'select',
    },
    {
      autoFocus: false,
      id: 'category',
      label: 'Categoria',
      multiple: false,
      name: 'category',
      options: [],
      placeholder: 'Selecione a categoria',
      required: true,
      type: 'select',
    },
    // {
    //   autoFocus: false,
    //   id: 'parent',
    //   label: 'parent',
    //   multiple: false,
    //   name: 'parent',
    //   options: [],
    //   placeholder: 'parent',
    //   required: false,
    //   type: 'text',
    // },
    {
      autoFocus: false,
      id: 'contractId',
      label: 'Contrato',
      multiple: false,
      name: 'contractId',
      options: [],
      placeholder: 'Selecione o contrato',
      required: false,
      type: 'select',
    },
    {
      autoFocus: false,
      id: 'departmentId',
      label: 'Departamento',
      multiple: false,
      name: 'departmentId',
      options: [],
      placeholder: 'Departamento',
      required: false,
      type: 'text',
    },
    {
      autoFocus: false,
      id: 'createdBy',
      label: 'createdBy',
      multiple: false,
      name: 'createdBy',
      options: [],
      placeholder: 'createdBy',
      required: false,
      type: 'text',
    },
    {
      autoFocus: false,
      id: 'contactName',
      label: 'contactName',
      multiple: false,
      name: 'contactName',
      options: [],
      placeholder: 'contactName',
      required: false,
      type: 'text',
    },
    {
      autoFocus: false,
      id: 'contactPhone',
      label: 'contactPhone',
      multiple: false,
      name: 'contactPhone',
      options: [],
      placeholder: 'contactPhone',
      required: false,
      type: 'text',
    },
    {
      autoFocus: false,
      id: 'contactEmail',
      label: 'contactEmail',
      multiple: false,
      name: 'contactEmail',
      options: [],
      placeholder: 'contactEmail',
      required: false,
      type: 'text',
    },
    {
      autoFocus: false,
      id: 'place',
      label: 'Local (referência)',
      multiple: false,
      name: 'place',
      options: [],
      placeholder: 'Local (referência)',
      required: false,
      type: 'text',
    },
    {
      autoFocus: false,
      id: 'progress',
      label: 'Progresso (%)',
      multiple: false,
      name: 'progress',
      options: [],
      placeholder: 'Progresso (%)',
      required: false,
      type: 'text',
    },
    {
      autoFocus: false,
      id: 'dateLimit',
      label: 'Prazo de conclusão',
      multiple: false,
      name: 'dateLimit',
      options: [],
      placeholder: 'dateLimit',
      required: false,
      type: 'date',
    },
    {
      autoFocus: false,
      id: 'dateStart',
      label: 'Início da execução',
      multiple: false,
      name: 'dateStart',
      options: [],
      placeholder: 'dateStart',
      required: false,
      type: 'date',
    },
    {
      autoFocus: false,
      id: 'dateEnd',
      label: 'Data de conclusão',
      multiple: false,
      name: 'dateEnd',
      options: [],
      placeholder: 'dateEnd',
      required: false,
      type: 'date',
    },
    {
      autoFocus: false,
      id: 'files',
      label: 'Arquivos anexos',
      multiple: true,
      name: 'files',
      options: [],
      placeholder: 'files',
      required: false,
      type: 'file',
    },
  ]
};