export const tableConfig = {
  numberOfColumns: 6,
  checkbox: true,
  checkboxWidth: "5%",
  itemPath: '/manutencao/os/view/',
  itemClickable: true,
  idAttributeForData: 'taskId',
  columns: [
    { name: 'orderId', description: 'OS', width: "10%", align: "center", data: ['orderId'] },
    { name: 'title', description: 'Título', width: "40%", align: "justify", wrap: true, data: ['title', 'category'] },
    { name: 'status', description: 'Status', width: "15%", align: "center", data: ['status'] },
    { name: 'dateLimit', description: 'Prazo Final', width: "15%", align: "center", data: ['dateLimit'] },
    { name: 'place', description: 'Localização', width: "15%", align: "center", data: ['place'] },
  ],
};

export const data = [
  { orderId: "001", category: "Reparo em Forro", title: "Troca de vidros quebradosTroca de vidros quebradosTroca de vidros quebradosTroca de vidros quebradosTroca de vidros quebradosTroca de vidros quebradosTroca de vidros quebradosTroca de vidros quebrados", status: "Canceladasssssssssssss", dateLimit: "12-10-2020", place: "Sala do SEMAC" },
  { orderId: "001", category: "Reparo em Forro", title: "Troca de vidros quebrados", status: "Cancelada", dateLimit: "12-10-2020", place: "Sala do SEMAC" },
  { orderId: "001", category: "Reparo em Forro", title: "Troca de vidros quebrados", status: "Canceladassssssssssssssssss", dateLimit: "12-10-2020", place: "Sala do SEMAC" },
  { orderId: "001", category: "Reparo em Forro", title: "Troca de vidros quebrados", status: "Cancelada", dateLimit: "12-10-2020", place: "Sala do SEMAC" },
  { orderId: "001", category: "Reparo em Forro", title: "Troca de vidros quebrados", status: "Cancelada", dateLimit: "12-10-2020", place: "Sala do SEMAC" },
  { orderId: "001", category: "Reparo em Forro", title: "Troca de vidros quebrados", status: "Cancelada", dateLimit: "12-10-2020", place: "Sala do SEMAC" },
  { orderId: "001", category: "Reparo em Forro", title: "Troca de vidros quebrados", status: "Cancelada", dateLimit: "12-10-2020", place: "Sala do SEMAC" },
  { orderId: "001", category: "Reparo em Forro", title: "Troca de vidros quebrados", status: "Cancelada", dateLimit: "12-10-2020", place: "Sala do SEMAC" },
  { orderId: "001", category: "Reparo em Forro", title: "Troca de vidros quebrados", status: "Cancelada", dateLimit: "12-10-2020", place: "Sala do SEMAC" },
  { orderId: "001", category: "Reparo em Forro", title: "Troca de vidros quebrados", status: "Cancelada", dateLimit: "12-10-2020", place: "Sala do SEMAC" },
  { orderId: "001", category: "Reparo em Forro", title: "Troca de vidros quebrados", status: "Cancelada", dateLimit: "12-10-2020", place: "Sala do SEMAC" },
  { orderId: "001", category: "Reparo em Forro", title: "Troca de vidros quebrados", status: "Cancelada", dateLimit: "12-10-2020", place: "Sala do SEMAC" },
  { orderId: "001", category: "Reparo em Forro", title: "Troca de vidros quebrados", status: "Cancelada", dateLimit: "12-10-2020", place: "Sala do SEMAC" },
  { orderId: "001", category: "Reparo em Forro", title: "Troca de vidros quebrados", status: "Cancelada", dateLimit: "12-10-2020", place: "Sala do SEMAC" },
  { orderId: "001", category: "Reparo em Forro", title: "Troca de vidros quebrados", status: "Cancelada", dateLimit: "12-10-2020", place: "Sala do SEMAC" },
  { orderId: "001", category: "Reparo em Forro", title: "Troca de vidros quebrados", status: "Cancelada", dateLimit: "12-10-2020", place: "Sala do SEMAC" },
  { orderId: "001", category: "Reparo em Forro", title: "Troca de vidros quebrados", status: "Cancelada", dateLimit: "12-10-2020", place: "Sala do SEMAC" },
  { orderId: "001", category: "Reparo em Forro", title: "Troca de vidros quebrados", status: "Cancelada", dateLimit: "12-10-2020", place: "Sala do SEMAC" },
  { orderId: "001", category: "Reparo em Forro", title: "Troca de vidros quebrados", status: "Cancelada", dateLimit: "12-10-2020", place: "Sala do SEMAC" },
  { orderId: "001", category: "Reparo em Forro", title: "Troca de vidros quebrados", status: "Cancelada", dateLimit: "12-10-2020", place: "Sala do SEMAC" },
  { orderId: "001", category: "Reparo em Forro", title: "Troca de vidros quebrados", status: "Cancelada", dateLimit: "12-10-2020", place: "Sala do SEMAC" },
  { orderId: "001", category: "Reparo em Forro", title: "Troca de vidros quebrados", status: "Cancelada", dateLimit: "12-10-2020", place: "Sala do SEMAC" },
  { orderId: "001", category: "Reparo em Forro", title: "Troca de vidros quebrados", status: "Cancelada", dateLimit: "12-10-2020", place: "Sala do SEMAC" },
  { orderId: "001", category: "Reparo em Forro", title: "Troca de vidros quebrados", status: "Cancelada", dateLimit: "12-10-2020", place: "Sala do SEMAC" },
];