comment on function authenticate is E'@omit execute';
comment on table assets is E'@omit create,update,delete';
comment on table asset_relations is E'@omit create,update,delete';
comment on table contracts is E'@omit create,update,delete';
-- comment on table departments is E'@omit create,update,delete';
comment on table persons is E'@omit all,create,update,delete';
comment on table teams is E'@omit create,update,delete';
comment on table team_persons is E'@omit create,update,delete';
comment on table contract_teams is E'@omit create,update,delete';
comment on table orders is E'@omit create,update,delete';
comment on table order_messages is E'@omit all,create,update,delete';
comment on table order_assets is E'@omit create,update,delete';
comment on table order_teams is E'@omit create,update,delete';
-- comment on table asset_departments is E'@omit create,update,delete';
comment on table specs is E'@omit all,create,update,delete';
comment on table supplies is E'@omit read,all,many,create,update,delete';
comment on table order_supplies is E'@omit all,create,update,delete';
comment on table rules is E'@omit create,update,delete';
comment on table asset_rules is E'@omit create,update,delete';
comment on table spec_rules is E'@omit create,update,delete';
comment on table templates is E'@omit create,update,delete';
comment on table asset_files is E'@omit create,update,delete';
comment on table order_files is E'@omit create,update,delete';
comment on table rule_files is E'@omit create,update,delete';
comment on table template_files is E'@omit create,update,delete';
comment on view appliances is E'@omit create,update,delete';
comment on view facilities is E'@omit create,update,delete';
-- comment on constraint persons_pkey on persons is E'@omit';
-- comment on constraint persons_email_key on persons is E'@omit';
-- comment on constraint contracts_pkey on contracts is E'@omit';
-- comment on constraint specs_pkey on specs is E'@omit';