insert into departments values ('SF', 'SF', 'Senado Federal', true);
insert into departments values ('COMDIR', 'SF', 'COMISSÃO DIRETORA', true);
insert into departments values ('PRVPRE', 'COMDIR', 'PRIMEIRA VICE-PRESIDÊNCIA', true);
insert into departments values ('SGVPRE', 'COMDIR', 'SEGUNDA VICE-PRESIDÊNCIA', true);
insert into departments values ('PRSECR', 'COMDIR', 'PRIMEIRA SECRETARIA', true);
insert into departments values ('SGSECR', 'COMDIR', 'SEGUNDA SECRETARIA', true);
insert into departments values ('TRSECR', 'COMDIR', 'TERCEIRA SECRETARIA', true);
insert into departments values ('QTSECR', 'COMDIR', 'QUARTA SECRETARIA', true);
insert into departments values ('PRSUPL', 'COMDIR', 'GABINETE DO PRIMEIRO SUPLENTE DE SECRETÁRIO', true);
insert into departments values ('SGSUPL', 'COMDIR', 'GABINETE DO SEGUNDO SUPLENTE DE SECRETÁRIO', true);
insert into departments values ('TRSUPL', 'COMDIR', 'GABINETE DO TERCEIRO SUPLENTE DE SECRETÁRIO', true);
insert into departments values ('QTSUPL', 'COMDIR', 'GABINETE DO QUARTO SUPLENTE DE SECRETÁRIO', true);
insert into departments values ('CEDIT', 'COMDIR', 'CONSELHO EDITORIAL', true);
insert into departments values ('CGCGE', 'COMDIR', 'COMITÊ DE GOVERNANÇA CORPORATIVA E GESTÃO ESTRATÉGICA', true);
insert into departments values ('COSILB', 'COMDIR', 'CONSELHO DE SUPERVISÃO DO ILB', true);
insert into departments values ('CSIS', 'COMDIR', 'CONSELHO DE SUPERVISÃO DO SISTEMA INTEGRADO DE SAÚDE(SIS)', true);
insert into departments values ('PRESID', 'SF', 'PRESIDÊNCIA', true);
insert into departments values ('CEPRES', 'PRESID', 'CERIMONIAL DA PRESIDENCIA', true);
insert into departments values ('SECOEV', 'CEPRES', 'SERVIÇO DE COORDENAÇÃO DE EVENTOS', true);
insert into departments values ('SEPGPR', 'CEPRES', 'SERVIÇO DE PLANEJAMENTO E GESTÃO', true);
insert into departments values ('SERAGE', 'CEPRES', 'SERVIÇO DE RECEPÇÃO E AGENDA', true);
insert into departments values ('GBPRES', 'PRESID', 'GABINETE DA PRESIDÊNCIA', true);
insert into departments values ('ASIMP', 'PRESID', 'ASSESSORIA DE IMPRENSA DA PRESIDÊNCIA', true);
insert into departments values ('ASPRES', 'PRESID', 'ASSESSORIA TÉCNICA DA PRESIDÊNCIA', true);
insert into departments values ('SERINT', 'PRESID', 'SECRETARIA DE RELAÇÕES INTERNACIONAIS DA PRESIDÊNCIA', true);
insert into departments values ('STRANS', 'PRESID', 'SECRETARIA DE TRANSPARÊNCIA', true);
insert into departments values ('ATSTRANS', 'STRANS', 'ASSESSORIA TÉCNICA DA STRANS', true);
insert into departments values ('DATASEN', 'STRANS', 'INSTITUTO DE PESQUISA DATASENADO', true);
insert into departments values ('SEGS', 'DATASEN', 'SERVIÇO DE GERENCIAMENTO DE SISTEMAS', true);
insert into departments values ('SEPEA', 'DATASEN', 'SERVIÇO DE PESQUISA E ANÁLISE', true);
insert into departments values ('OMV', 'DATASEN', 'OBSERVATÓRIO DA MULHER CONTRA A VIOLÊNCIA', true);
insert into departments values ('DATJUR', 'PRESID', 'DIRETORIA DE ASSUNTOS TÉCNICOS E JURÍDICOS', true);
insert into departments values ('GABSEN', 'SF', 'GABINETES DOS SENADORES', true);
insert into departments values ('GSAANAST', 'GABSEN', 'GABINETE DO SENADOR ANTONIO ANASTASIA', true);
insert into departments values ('E1AANAST', 'GSAANAST', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR ANTONIO ANASTASIA', true);
insert into departments values ('GSACORON', 'GABSEN', 'GABINETE DO SENADOR ANGELO CORONEL', true);
insert into departments values ('E1ACORON', 'GSACORON', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR ANGELO CORONEL', true);
insert into departments values ('GSADIA', 'GABSEN', 'GABINETE DO SENADOR ALVARO DIAS', true);
insert into departments values ('EAADIA', 'GSADIA', 'ESCRITÓRIO DE AP. Nº 01 DO SENADOR ALVARO DIAS', true);
insert into departments values ('GSAGUR', 'GABSEN', 'GABINETE DO SENADOR ACIR GURGACZ', true);
insert into departments values ('EAAGUR', 'GSAGUR', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR ACIR GURGACZ', true);
insert into departments values ('GSAOLIVE', 'GABSEN', 'GABINETE DO SENADOR AROLDE DE OLIVEIRA', true);
insert into departments values ('E1AOLIVE', 'GSAOLIVE', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR AROLDE DE OLIVEIRA', true);
insert into departments values ('GSAVIEIR', 'GABSEN', 'GABINETE DO SENADOR ALESSANDRO VIEIRA', true);
insert into departments values ('E1AVIEIR', 'GSAVIEIR', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR ALESSANDRO VIEIRA', true);
insert into departments values ('GSCGOMES', 'GABSEN', 'GABINETE DO SENADOR CID GOMES', true);
insert into departments values ('E1CGOMES', 'GSCGOMES', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR CID GOMES', true);
insert into departments values ('GSCMOURA', 'GABSEN', 'GABINETE DO SENADOR CONFÚCIO MOURA', true);
insert into departments values ('E1CMOURA', 'GSCMOURA', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR SENADOR CONFÚCIO MOURA', true);
insert into departments values ('GSCNOG', 'GABSEN', 'GABINETE DO SENADOR CIRO NOGUEIRA', true);
insert into departments values ('E1CNOG', 'GSCNOG', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR CIRO NOGUEIRA', true);
insert into departments values ('GSCRODRI', 'GABSEN', 'GABINETE DO SENADOR CHICO RODRIGUES', true);
insert into departments values ('E1CRODRI', 'GSCRODRI', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR CHICO RODRIGUES', true);
insert into departments values ('GSCVIANA', 'GABSEN', 'GABINETE DO SENADOR CARLOS VIANA', true);
insert into departments values ('E1CVIANA', 'GSCVIANA', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR CARLOS VIANA', true);
insert into departments values ('GSDALCOL', 'GABSEN', 'GABINETE DO SENADOR DAVI ALCOLUMBRE', true);
insert into departments values ('E1DALCOL', 'GSDALCOL', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR DAVI ALCOLUMBRE', true);
insert into departments values ('GSDBERGE', 'GABSEN', 'GABINETE DO SENADOR DÁRIO BERGER', true);
insert into departments values ('E1DBERGE', 'GSDBERGE', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR DÁRIO BERGER', true);
insert into departments values ('GSDRIBEI', 'GABSEN', 'GABINETE DA SENADORA DANIELLA RIBEIRO', true);
insert into departments values ('E1DRIBEI', 'GSDRIBEI', 'ESCRITÓRIO DE APOIO Nº 01 DA SENADORA DANIELLA RIBEIRO', true);
insert into departments values ('GSEAMI', 'GABSEN', 'GABINETE DO SENADOR ESPERIDIÃO AMIN', true);
insert into departments values ('E1EAMI', 'GSEAMI', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR ESPERIDIÃO AMIN', true);
insert into departments values ('GSEBRA', 'GABSEN', 'GABINETE DO SENADOR EDUARDO BRAGA', true);
insert into departments values ('E1EBRA', 'GSEBRA', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR EDUARDO BRAGA', true);
insert into departments values ('GSEFERRE', 'GABSEN', 'GABINETE DO SENADOR ELMANO FÉRRER', true);
insert into departments values ('E1EFERRE', 'GSEFERRE', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR ELMANO FÉRRER', true);
insert into departments values ('GSEGAMA', 'GABSEN', 'GABINETE DA SENADORA ELIZIANE GAMA', true);
insert into departments values ('E1EGAMA', 'GSEGAMA', 'ESCRITÓRIO DE APOIO Nº 01 DA SENADORA ELIZIANE GAMA', true);
insert into departments values ('GSEGIRAO', 'GABSEN', 'GABINETE DO SENADOR EDUARDO GIRÃO', true);
insert into departments values ('E1EGIRAO', 'GSEGIRAO', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR EDUARDO GIRÃO', true);
insert into departments values ('GSFARN', 'GABSEN', 'GABINETE DO SENADOR FLÁVIO ARNS', true);
insert into departments values ('EAFARN', 'GSFARN', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR FLÁVIO ARNS', true);
insert into departments values ('GSFB', 'GABSEN', 'GABINETE DO SENADOR FLÁVIO BOLSONARO', true);
insert into departments values ('E1FB', 'GSFB', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR FLÁVIO BOLSONARO', true);
insert into departments values ('GSFCONTA', 'GABSEN', 'GABINETE DO SENADOR FABIANO CONTARATO', true);
insert into departments values ('E1FCONTA', 'GSFCONTA', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR FABIANO CONTARATO', true);
insert into departments values ('GSFERCOE', 'GABSEN', 'GABINETE DO SENADOR FERNANDO BEZERRA COELHO', true);
insert into departments values ('E1FERCOE', 'GSFERCOE', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR FERNANDO BEZERRA COELHO', true);
insert into departments values ('E2FERCOE', 'GSFERCOE', 'ESCRITÓRIO DE APOIO Nº 02 DO SENADOR FERNANDO BEZERRA COELHO', true);
insert into departments values ('GSHCST', 'GABSEN', 'GABINETE DO SENADOR HUMBERTO COSTA', true);
insert into departments values ('E1HCST', 'GSHCST', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR HUMBERTO COSTA', true);
insert into departments values ('E2HCST', 'GSHCST', 'ESCRITÓRIO DE APOIO Nº 02 DO SENADOR HUMBERTO COSTA', true);
insert into departments values ('GSIRAJA', 'GABSEN', 'GABINETE DO SENADOR IRAJÁ', true);
insert into departments values ('E1IRAJA', 'GSIRAJA', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR IRAJÁ', true);
insert into departments values ('GSIZALCI', 'GABSEN', 'GABINETE DO SENADOR IZALCI LUCAS', true);
insert into departments values ('E1IZALCI', 'GSIZALCI', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR IZALCI LUCAS', true);
insert into departments values ('GSJAYM', 'GABSEN', 'GABINETE DO SENADOR JAYME CAMPOS', true);
insert into departments values ('E1JAYM', 'GSJAYM', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR JAYME CAMPOS', true);
insert into departments values ('GSJBAR', 'GABSEN', 'GABINETE DO SENADOR JADER BARBALHO', true);
insert into departments values ('E1JBAR', 'GSJBAR', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR JADER BABALHO', true);
insert into departments values ('GSJKAJUR', 'GABSEN', 'GABINETE DO SENADOR JORGE KAJURU', true);
insert into departments values ('E1JKAJUR', 'GSJKAJUR', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR JORGE KAJURU', true);
insert into departments values ('GSJMAR', 'GABSEN', 'GABINETE DO SENADOR JOSÉ MARANHÃO', true);
insert into departments values ('E1JMAR', 'GSJMAR', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR JOSÉ MARANHÃO', true);
insert into departments values ('GSJMELLO', 'GABSEN', 'GABINETE DO SENADOR JORGINHO MELLO', true);
insert into departments values ('E1JMELLO', 'GSJMELLO', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR JORGINHO MELLO', true);
insert into departments values ('GSJPRAT', 'GABSEN', 'GABINETE DO SENADOR JEAN PAUL PRATES', true);
insert into departments values ('E1JPRAT', 'GSJPRAT', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR JEAN PAUL PRATES', true);
insert into departments values ('GSJSELMA', 'GABSEN', 'GABINETE DA SENADORA JUÍZA SELMA', true);
insert into departments values ('E1JSELMA', 'GSJSELMA', 'ESCRITÓRIO DE APOIO Nº 01 DA SENADORA JUÍZA SELMA', true);
insert into departments values ('GSJSER', 'GABSEN', 'GABINETE DO SENADOR JOSÉ SERRA', true);
insert into departments values ('E1JSER', 'GSJSER', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR JOSÉ SERRA', true);
insert into departments values ('GSJVAS', 'GABSEN', 'GABINETE DO SENADOR JARBAS VASCONCELOS', true);
insert into departments values ('EAJVAS', 'GSJVAS', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR JARBAS VASCONCELOS', true);
insert into departments values ('GSJWAG', 'GABSEN', 'GABINETE DO SENADOR JAQUES WAGNER', true);
insert into departments values ('E1JWAG', 'GSJWAG', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR JAQUES WAGNER', true);
insert into departments values ('GSKAAB', 'GABSEN', 'GABINETE DA SENADORA KÁTIA ABREU', true);
insert into departments values ('EAKAAB', 'GSKAAB', 'ESCRITÓRIO DE APOIO Nº 01 DA SENADORA KÁTIA ABREU', true);
insert into departments values ('E2KAAB', 'GSKAAB', 'ESCRITÓRIO DE APOIO Nº 02 DA SENADORA KÁTIA ABREU', true);
insert into departments values ('GSLBARRE', 'GABSEN', 'GABINETE DO SENADOR LUCAS BARRETO', true);
insert into departments values ('E1LBARRE', 'GSLBARRE', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR LUCAS BARRETO', true);
insert into departments values ('GSLCARM', 'GABSEN', 'GABINETE DO SENADOR LUIZ CARLOS DO CARMO', true);
insert into departments values ('E1LCARM', 'GSLCARM', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR LUIZ CARLOS DO CARMO', true);
insert into departments values ('GSLEILAB', 'GABSEN', 'GABINETE DA SENADORA LEILA BARROS', true);
insert into departments values ('E1LEILAB', 'GSLEILAB', 'ESCRITÓRIO DE APOIO Nº 01 DA SENADORA LEILA BARROS', true);
insert into departments values ('GSLHEINZ', 'GABSEN', 'GABINETE DO SENADOR LUIS CARLOS HEINZE', true);
insert into departments values ('E1LHEINZ', 'GSLHEINZ', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR LUIS CARLOS HEINZE', true);
insert into departments values ('E2LHEINZ', 'GSLHEINZ', 'ESCRITÓRIO DE APOIO Nº 02 DO SENADOR LUIS CARLOS HEINZE', true);
insert into departments values ('GSLMARTI', 'GABSEN', 'GABINETE DO SENADOR LASIER MARTINS', true);
insert into departments values ('E1LMARTI', 'GSLMARTI', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR LASIER MARTINS', true);
insert into departments values ('GSMALV', 'GABSEN', 'GABINETE DA SENADORA MARIA DO CARMO ALVES', true);
insert into departments values ('EAMALV', 'GSMALV', 'ESCRITÓRIO DE APOIO Nº 01 DA SENADORA MARIA DO CARMO ALVES', true);
insert into departments values ('GSMBITTA', 'GABSEN', 'GABINETE DO SENADOR MARCIO BITTAR', true);
insert into departments values ('E1MBITTA', 'GSMBITTA', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR MARCIO BITTAR', true);
insert into departments values ('GSMCASTR', 'GABSEN', 'GABINETE DO SENADOR MARCELO CASTRO', true);
insert into departments values ('E1MCASTR', 'GSMCASTR', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR MARCELO CASTRO', true);
insert into departments values ('GSMGABRI', 'GABSEN', 'GABINETE DA SENADORA MARA GABRILLI', true);
insert into departments values ('E1MGABRI', 'GSMGABRI', 'ESCRITÓRIO DE APOIO Nº 01 DA SENADORA MARA GABRILLI', true);
insert into departments values ('GSMGOM', 'GABSEN', 'GABINETE DA SENADORA MAILZA GOMES', true);
insert into departments values ('EAMGOM', 'GSMGOM', 'ESCRITÓRIO DE APOIO N°01 DA SENADORA MAILZA GOMES', true);
insert into departments values ('GSMJESUS', 'GABSEN', 'GABINETE DO SENADOR MECIAS DE JESUS', true);
insert into departments values ('E1MJESUS', 'GSMJESUS', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR MECIAS DE JESUS', true);
insert into departments values ('GSMROGER', 'GABSEN', 'GABINETE DO SENADOR MARCOS ROGÉRIO', true);
insert into departments values ('E1MROGER', 'GSMROGER', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR MARCOS ROGÉRIO', true);
insert into departments values ('GSMVAL', 'GABSEN', 'GABINETE DO SENADOR MARCOS DO VAL', true);
insert into departments values ('E1MVAL', 'GSMVAL', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR MARCOS DO VAL', true);
insert into departments values ('GSNTRAD', 'GABSEN', 'GABINETE DO SENADOR NELSINHO TRAD', true);
insert into departments values ('E1NTRAD', 'GSNTRAD', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR NELSINHO TRAD', true);
insert into departments values ('GSOALENC', 'GABSEN', 'GABINETE DO SENADOR OTTO ALENCAR', true);
insert into departments values ('E1OALENC', 'GSOALENC', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR OTTO ALENCAR', true);
insert into departments values ('GSOAZIZ', 'GABSEN', 'GABINETE DO SENADOR OMAR AZIZ', true);
insert into departments values ('E1OAZIZ', 'GSOAZIZ', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR OMAR AZIZ', true);
insert into departments values ('GSOGUIMA', 'GABSEN', 'GABINETE DO SENADOR ORIOVISTO GUIMARÃES', true);
insert into departments values ('E1OGUIMA', 'GSOGUIMA', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR ORIOVISTO GUIMARÃES', true);
insert into departments values ('GSOLIMPI', 'GABSEN', 'GABINETE DO SENADOR MAJOR OLIMPIO', true);
insert into departments values ('E1OLIMPI', 'GSOLIMPI', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR MAJOR OLIMPIO', true);
insert into departments values ('GSPAULOR', 'GABSEN', 'GABINETE DO SENADOR PAULO ROCHA', true);
insert into departments values ('E1PAULOR', 'GSPAULOR', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR PAULO ROCHA', true);
insert into departments values ('GSPPAI', 'GABSEN', 'GABINETE DO SENADOR PAULO PAIM', true);
insert into departments values ('EAPPAI', 'GSPPAI', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR PAULO PAIM', true);
insert into departments values ('GSPVALER', 'GABSEN', 'GABINETE DO SENADOR PLÍNIO VALÉRIO', true);
insert into departments values ('E1PVALER', 'GSPVALER', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR PLÍNIO VALÉRIO', true);
insert into departments values ('GSRBULH', 'GABSEN', 'GABINETE DA SENADORA RENILDE BULHÕES', true);
insert into departments values ('E1RBULH', 'GSRBULH', 'ESCRITÓRIO DE APOIO Nº 01 DA SENADORA RENILDE BULHÕES', true);
insert into departments values ('GSRCAL', 'GABSEN', 'GABINETE DO SENADOR RENAN CALHEIROS', true);
insert into departments values ('EARCAL', 'GSRCAL', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR RENAN CALHEIROS', true);
insert into departments values ('GSRCUNHA', 'GABSEN', 'GABINETE DO SENADOR RODRIGO CUNHA', true);
insert into departments values ('E1RCUNHA', 'GSRCUNHA', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR RODRIGO CUNHA', true);
insert into departments values ('GSREGUFF', 'GABSEN', 'GABINETE DO SENADOR REGUFFE', true);
insert into departments values ('GSRFREIT', 'GABSEN', 'GABINETE DA SENADORA ROSE DE FREITAS', true);
insert into departments values ('E1RFREIT', 'GSRFREIT', 'ESCRITÓRIO DE APOIO Nº 01 DA SENADORA ROSE DE FREITAS', true);
insert into departments values ('GSROMARI', 'GABSEN', 'GABINETE DO SENADOR ROMÁRIO', true);
insert into departments values ('E1ROMARI', 'GSROMARI', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR ROMÁRIO', true);
insert into departments values ('GSRPACHE', 'GABSEN', 'GABINETE DO SENADOR RODRIGO PACHECO', true);
insert into departments values ('E1RPACHE', 'GSRPACHE', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR RODRIGO PACHECO', true);
insert into departments values ('GSRROCHA', 'GABSEN', 'GABINETE DO SENADOR ROBERTO ROCHA', true);
insert into departments values ('E1RROCHA', 'GSRROCHA', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR ROBERTO ROCHA', true);
insert into departments values ('GSRROD', 'GABSEN', 'GABINETE DO SENADOR RANDOLFE RODRIGUES', true);
insert into departments values ('E1RROD', 'GSRROD', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR RANDOLFE RODRIGUES', true);
insert into departments values ('GSRSANT', 'GABSEN', 'GABINETE DO SENADOR ROGÉRIO CARVALHO', true);
insert into departments values ('E1RSANT', 'GSRSANT', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR ROGÉRIO CARVALHO', true);
insert into departments values ('GSSCAM', 'GABSEN', 'GABINETE DO SENADOR SIQUEIRA CAMPOS', true);
insert into departments values ('GSSCASTR', 'GABSEN', 'GABINETE DO SENADOR SÉRGIO DE CASTRO', true);
insert into departments values ('E1SCASTR', 'GSSCASTR', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR SÉRGIO DE CASTRO', true);
insert into departments values ('GSSPET', 'GABSEN', 'GABINETE DO SENADOR SÉRGIO PETECÃO', true);
insert into departments values ('E1SPET', 'GSSPET', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR SÉRGIO PETECÃO', true);
insert into departments values ('GSSTEBET', 'GABSEN', 'GABINETE DA SENADORA SIMONE TEBET', true);
insert into departments values ('E1STEBET', 'GSSTEBET', 'ESCRITÓRIO DE APOIO Nº 01 DA SENADORA SIMONE TEBET', true);
insert into departments values ('GSSTHRON', 'GABSEN', 'GABINETE DA SENADORA SORAYA THRONICKE', true);
insert into departments values ('E1STHRON', 'GSSTHRON', 'ESCRITÓRIO DE APOIO Nº 01 DA SENADORA SORAYA THRONICKE', true);
insert into departments values ('GSSTYVEN', 'GABSEN', 'GABINETE DO SENADOR STYVENSON VALENTIM', true);
insert into departments values ('E1STYVEN', 'GSSTYVEN', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR STYVENSON VALENTIM', true);
insert into departments values ('GSTJER', 'GABSEN', 'GABINETE DO SENADOR TASSO JEREISSATI', true);
insert into departments values ('EATJER', 'GSTJER', 'ESCRITÓRIO DE AP. Nº 01 DO SENADOR TASSO JEREISSATI', true);
insert into departments values ('GSTMOTA', 'GABSEN', 'GABINETE DO SENADOR TELMÁRIO MOTA', true);
insert into departments values ('E1TMOTA', 'GSTMOTA', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR TELMÁRIO MOTA', true);
insert into departments values ('GSTPINTO', 'GABSEN', 'GABINETE DO SENADOR THIERES PINTO', true);
insert into departments values ('E1TPINTO', 'GSTPINTO', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR THIERES PINTO', true);
insert into departments values ('GSVANDER', 'GABSEN', 'GABINETE DO SENADOR VANDERLAN CARDOSO', true);
insert into departments values ('E1VANDER', 'GSVANDER', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR VANDERLAN CARDOSO', true);
insert into departments values ('GSVENEZI', 'GABSEN', 'GABINETE DO SENADOR VENEZIANO VITAL DO RÊGO', true);
insert into departments values ('E1VENEZI', 'GSVENEZI', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR VENEZIANO VITAL RÊGO', true);
insert into departments values ('GSWEVERT', 'GABSEN', 'GABINETE DO SENADOR WEVERTON ROCHA', true);
insert into departments values ('E1WEVERT', 'GSWEVERT', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR WEVERTON ROCHA', true);
insert into departments values ('GSWFAGUN', 'GABSEN', 'GABINETE DO SENADOR WELLINGTON FAGUNDES', true);
insert into departments values ('E1WFAGUN', 'GSWFAGUN', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR WELLINGTON FAGUNDES', true);
insert into departments values ('E2WFAGUN', 'GSWFAGUN', 'ESCRITÓRIO DE APOIO Nº 02 DO SENADOR WELLINGTON FAGUNDES', true);
insert into departments values ('GSZMAIA', 'GABSEN', 'GABINETE DA SENADORA ZENAIDE MAIA', true);
insert into departments values ('E1ZMAIA', 'GSZMAIA', 'ESCRITÓRIO DE APOIO Nº 01 DA SENADORA ZENAIDE MAIA', true);
insert into departments values ('GSZMARIN', 'GABSEN', 'GABINETE DO SENADOR ZEQUINHA MARINHO', true);
insert into departments values ('E1ZMARIN', 'GSZMARIN', 'ESCRITÓRIO DE APOIO Nº 01 DO SENADOR ZEQUINHA MARINHO', true);
insert into departments values ('GABLID', 'SF', 'GABINETES DE LIDERANÇAS', true);
insert into departments values ('BLMCON', 'GABLID', 'BLOCO DA LIDERANÇA DA MINORIA NO CONGRESSO NACIONAL', true);
insert into departments values ('BLPP', 'GABLID', 'BLOCO PARLAMENTAR PSDB/PSL', true);
insert into departments values ('BLPRD', 'GABLID', 'BLOCO PARLAMENTAR DA RESISTÊNCIA DEMOCRÁTICA', true);
insert into departments values ('BLSENIND', 'GABLID', 'BLOCO PARLAMENTAR SENADO INDEPENDENTE', true);
insert into departments values ('BLUNIDB', 'GABLID', 'BLOCO PARLAMENTAR UNIDOS PELO BRASIL', true);
insert into departments values ('BLVANG', 'GABLID', 'BLOCO PARLAMENTAR VANGUARDA', true);
insert into departments values ('GLCID', 'GABLID', 'GABINETE DA LIDERANÇA DO CIDADANIA', true);
insert into departments values ('GLDEM', 'GABLID', 'GABINETE DA LIDERANÇA DOS DEMOCRATAS', true);
insert into departments values ('GLDGCN', 'GABLID', 'GABINETE DA LIDERANÇA DO GOVERNO NO CONGRESSO NACIONAL', true);
insert into departments values ('GLDGOV', 'GABLID', 'GABINETE DA LIDERANÇA DO GOVERNO', true);
insert into departments values ('GLDMAI', 'GABLID', 'GABINETE DA LIDERANÇA DO BLOCO DA MAIORIA', true);
insert into departments values ('GLDMIN', 'GABLID', 'GABINETE DA LIDERANÇA DO BLOCO DA MINORIA', true);
insert into departments values ('GLDPDT', 'GABLID', 'GABINETE DA LIDERANÇA DO PDT', true);
insert into departments values ('GLDPP', 'GABLID', 'GABINETE DA LIDERANÇA DO PARTIDO PROGRESSISTA', true);
insert into departments values ('GLDPR', 'GABLID', 'GABINETE DA LIDERANÇA DO PARTIDO DA REPUBLICA', true);
insert into departments values ('GLDPSB', 'GABLID', 'GABINETE DA LIDERANÇA DO PSB', true);
insert into departments values ('GLDPT', 'GABLID', 'GABINETE DA LIDERANÇA DO PT', true);
insert into departments values ('GLIDPSL', 'GABLID', 'GABINETE DA LIDERANÇA DO PSL', true);
insert into departments values ('GLMDB', 'GABLID', 'GABINETE DA LIDERANÇA DO MDB', true);
insert into departments values ('GLPL', 'GABLID', 'GABINETE DA LIDERANÇA DO PARTIDO LIBERAL', true);
insert into departments values ('GLPODEMOS', 'GABLID', 'GABINETE DA LIDERANÇA DO PODEMOS', true);
insert into departments values ('GLPPL', 'GABLID', 'GABINETE DA LIDERANÇA DO PPL', true);
insert into departments values ('GLPRB', 'GABLID', 'GABINETE DA LIDERANÇA DO PRB', true);
insert into departments values ('GLPROS', 'GABLID', 'GABINETE DA LIDERANÇA DO PARTIDO REPUBLICANO DA ORDEM SOCIAL – PROS', true);
insert into departments values ('GLPSC', 'GABLID', 'GABINETE DA LIDERANÇA DO PSC', true);
insert into departments values ('GLPSD', 'GABLID', 'GABINETE DA LIDERANÇA DO PSD', true);
insert into departments values ('GLPSDB', 'GABLID', 'GABINETE DA LIDERANÇA DO PSDB', true);
insert into departments values ('GLPV', 'GABLID', 'GABINETE DA LIDERANÇA DO PV', true);
insert into departments values ('GLREDE', 'GABLID', 'GABINETE DA LIDERANÇA DO REDE SUSTENTABILIDADE', true);
insert into departments values ('OSE', 'SF', 'ÓRGÃOS SUPERIORES DE EXECUÇÃO', true);
insert into departments values ('DGER', 'OSE', 'DIRETORIA-GERAL', true);
insert into departments values ('GBDGER', 'DGER', 'GABINETE DA DIRETORIA GERAL', true);
insert into departments values ('SEADGR', 'GBDGER', 'SERVIÇO DE APOIO ADMINISTRATIVO DO GBDGER', true);
insert into departments values ('EDGER', 'GBDGER', 'ESCRITÓRIO SETORIAL DE GESTÃO DA DGER', true);
insert into departments values ('ASQUALOG', 'DGER', 'ASSESSORIA DE QUALIDADE DE ATENDIMENTO E LOGÍSTICA', true);
insert into departments values ('SEGEPAVI', 'ASQUALOG', 'SERVIÇO DE GESTÃO DE PASSAGENS AÉREAS, PASSAPORTES E VISTOS', true);
insert into departments values ('SEQUALOG', 'ASQUALOG', 'SERVIÇO DE APOIO ADMINISTRATIVO DA ASQUALOG', true);
insert into departments values ('ATDGER', 'DGER', 'ASSESSORIA TÉCNICA DA DIRETORIA-GERAL', true);
insert into departments values ('PRDSTI', 'DGER', 'SECRETARIA DE TECNOLOGIA DA INFORMAÇÃO PRODASEN', true);
insert into departments values ('GBPRD', 'PRDSTI', 'GABINETE ADMINISTRATIVO DO PRODASEN', true);
insert into departments values ('SACTI', 'PRDSTI', 'SERVIÇO DE APOIO ÀS CONTRATAÇÕES DE TI', true);
insert into departments values ('COATEN', 'PRDSTI', 'COORDENAÇÃO DE ATENDIMENTO', true);
insert into departments values ('SAEQUI', 'COATEN', 'SERVIÇO DE ADMINISTRAÇÃO DE EQUIPAMENTOS', true);
insert into departments values ('SEAATE', 'COATEN', 'SERVIÇO DE APOIO ADMINISTRATIVO DA COATEN', true);
insert into departments values ('SEADMT', 'COATEN', 'SERVIÇO DE ATENDIMENTO ADMINISTRATIVO', true);
insert into departments values ('SEARE', 'COATEN', 'SERVIÇO DE ATENDIMENTO ÀS ÁREAS ESPECIAIS', true);
insert into departments values ('SEARP', 'COATEN', 'SERVIÇO DE ATENDIMENTO REMOTO E PRESENCIAL', true);
insert into departments values ('SEATLE', 'COATEN', 'SERVIÇO DE ATENDIMENTO LEGISLATIVO', true);
insert into departments values ('SEMOTI', 'COATEN', 'SERVIÇO DE CONTROLE DE QUALIDADE E MONITORAÇÃO DA PLATAFORMA DE TECNOLOGIA DA INFORMAÇÃO', true);
insert into departments values ('SEPARL', 'COATEN', 'SERVIÇO DE ATENDIMENTO PARLAMENTAR', true);
insert into departments values ('SERMAN', 'COATEN', 'SERVIÇO DE RELACIONAMENTO COM MANTENEDORES', true);
insert into departments values ('COINTI', 'PRDSTI', 'COORDENAÇÃO DE INFRAESTRUTURA DE TECNOLOGIA DA INFORMAÇÃO', true);
insert into departments values ('SEAINT', 'COINTI', 'SERVIÇO DE APOIO ADMINISTRATIVO DA COINTI', true);
insert into departments values ('SEINDC', 'COINTI', 'SERVIÇO DE APOIO À INFRAESTRUTURA DE DATACENTER', true);
insert into departments values ('SEPRTI', 'COINTI', 'SERVIÇO DE PRODUÇÃO DA COINTI', true);
insert into departments values ('SESBD', 'COINTI', 'SERVIÇO DE SUPORTE A BANCO DE DADOS', true);
insert into departments values ('SESIA', 'COINTI', 'SERVIÇO DE SUPORTE À INFRAESTRUTURA DE APLICAÇÕES', true);
insert into departments values ('SESIER', 'COINTI', 'SERVIÇO DE SUPORTE À INFRAESTRUTURA DE REDE', true);
insert into departments values ('SESIET', 'COINTI', 'SERVIÇO DE SUPORTE À INFRAESTRUTURA E ESTAÇÕES DE TRABALHO', true);
insert into departments values ('SESSR', 'COINTI', 'SERVIÇO DE SUPORTE A EQUIPAMENTOS SERVIDORES DE REDE', true);
insert into departments values ('SGMD', 'COINTI', 'SERVIÇO DE GERÊNCIA DE MUDANÇAS', true);
insert into departments values ('COLEP', 'PRDSTI', 'COORDENAÇÃO DE INFORMÁTICA LEGISLATIVA E PARLAMENTAR', true);
insert into departments values ('SEALEP', 'COLEP', 'SERVIÇO DE APOIO ADMINISTRATIVO DA COLEP', true);
insert into departments values ('SECN', 'COLEP', 'SERVIÇO DE SOLUÇÕES PARA O CONGRESSO NACIONAL', true);
insert into departments values ('SEDSVE', 'COLEP', 'SERVIÇO DE DESENVOLVIMENTO DO SISTEMA DE VOTAÇÃO ELETRÔNICA', true);
insert into departments values ('SEGAB', 'COLEP', 'SERVIÇO DE SOLUÇÕES PARA GABINETES PARLAMENTARES', true);
insert into departments values ('SELEJU', 'COLEP', 'SERVIÇO DE SOLUÇÕES PARA INFORMAÇÃO LEGISLATIVA E JURÍDICA', true);
insert into departments values ('SEPLE', 'COLEP', 'SERVIÇO DE SOLUÇÕES PARA O PROCESSO LEGISLATIVO ELETRÔNICO', true);
insert into departments values ('SESAP', 'COLEP', 'SERVIÇO DE SOLUÇÕES PARA A ATIVIDADE PARLAMENTAR E CONSULTORIAS', true);
insert into departments values ('SESCOM', 'COLEP', 'SERVIÇO DE SOLUÇÕES PARA AS COMISSÕES', true);
insert into departments values ('SESOF', 'COLEP', 'SERVIÇO DE SOLUÇÕES PARA O ORÇAMENTO E FISCALIZAÇÃO', true);
insert into departments values ('SESPLE', 'COLEP', 'SERVIÇO DE SOLUÇÕES PARA O PLENÁRIO', true);
insert into departments values ('COSTIC', 'PRDSTI', 'COORDENAÇÃO DE SOLUÇÕES DE TECNOLOGIA DA INFORMAÇÃO CORPORATIVA', true);
insert into departments values ('SEAIND', 'COSTIC', 'SERVIÇO DE ARQUITETURA DA INFORMAÇÃO E DESIGN', true);
insert into departments values ('SEATIC', 'COSTIC', 'SERVIÇO DE APOIO ADMINISTRATIVO DA COSTIC', true);
insert into departments values ('SEIDIC', 'COSTIC', 'SERVIÇO DE SOLUÇÕES PARA ÁREAS DE INFORMAÇÃO, DOCUMENTAÇÃO E COMUNICAÇÃO SOCIAL', true);
insert into departments values ('SEPOR', 'COSTIC', 'SERVIÇO DE SOLUÇÕES PARA PORTAIS', true);
insert into departments values ('SESADM', 'COSTIC', 'SERVIÇO DE SOLUÇÕES PARA ÁREAS TÉCNICAS E ADMINISTRATIVAS', true);
insert into departments values ('SESAS', 'COSTIC', 'SERVIÇO DE SOLUÇÕES PARA ÁREAS DE ASSESSORAMENTO SUPERIOR', true);
insert into departments values ('SESIC', 'COSTIC', 'SERVIÇO DE SOLUÇÕES DE INTELIGÊNCIA CORPORATIVA', true);
insert into departments values ('SESOC', 'COSTIC', 'SERVIÇO DE SOLUÇÕES CORPORATIVAS', true);
insert into departments values ('SESRH', 'COSTIC', 'SERVIÇO DE SOLUÇÕES PARA ÁREA DE RECURSOS HUMANOS', true);
insert into departments values ('EPRD', 'PRDSTI', 'ESCRITÓRIO SETORIAL DE GESTÃO DO PRODASEN', true);
insert into departments values ('NQPPPS', 'PRDSTI', 'NÚCLEO DE QUALIDADE E PADRONIZAÇÃO DE PROCESSOS E PRODUTOS DE SOFTWARE', true);
insert into departments values ('SADCON', 'DGER', 'SECRETARIA DE ADMINISTRAÇÃO DE CONTRATAÇÕES', true);
insert into departments values ('COATC', 'SADCON', 'COORDENAÇÃO DE APOIO TÉCNICO A CONTRATAÇÕES', true);
insert into departments values ('SACT', 'COATC', 'SERVIÇO DE APOIO A CONTRATAÇÕES EM TECNOLOGIA', true);
insert into departments values ('SEEDIT', 'COATC', 'SERVIÇO DE ELABORAÇÃO DE EDITAIS', true);
insert into departments values ('SEELAC', 'COATC', 'SERVIÇO DE ELABORAÇÃO DE CONTRATOS', true);
insert into departments values ('COCDIR', 'SADCON', 'COORDENAÇÃO DE CONTRATAÇÕES DIRETAS', true);
insert into departments values ('SEECON', 'COCDIR', 'SERVIÇO DE EXECUÇÃO DE CONTRATOS', true);
insert into departments values ('SEEXCO', 'COCDIR', 'SERVIÇO DE EXECUÇÃO DE COMPRAS', true);
insert into departments values ('SEGREP', 'COCDIR', 'SERVIÇO DE GERENCIAMENTO DE REGISTRO DE PREÇOS', true);
insert into departments values ('COCVAP', 'SADCON', 'COORDENAÇÃO DE CONTROLE E VALIDAÇÃO DE PROCESSOS', true);
insert into departments values ('SELESC', 'COCVAP', 'SERVIÇO DE ELABORAÇÃO DE ESTIMATIVA DE CUSTOS', true);
insert into departments values ('COPLAC', 'SADCON', 'COORDENAÇÃO DE PLANEJAMENTO E CONTROLE DE CONTRATAÇÕES', true);
insert into departments values ('SECON', 'COPLAC', 'SERVIÇO DE CONTRATOS', true);
insert into departments values ('SEINPE', 'COPLAC', 'SERVIÇO DE INSTRUÇÃO DE PENALIDADES', true);
insert into departments values ('SEPCO', 'COPLAC', 'SERVIÇO DE PLANEJAMENTO E CONTROLE', true);
insert into departments values ('SIRC', 'COPLAC', 'SERVIÇO DE INSTRUÇÃO DE REAJUSTES CONTRATUAIS', true);
insert into departments values ('COPELI', 'SADCON', 'COMISSÃO PERMANENTE DE LICITAÇÃO', true);
insert into departments values ('SEACPL', 'COPELI', 'SERVIÇO DE APOIO ADMINISTRATIVO DA COPELI', true);
insert into departments values ('SECADFOR', 'COPELI', 'SERVIÇO DE CADASTRO DE FORNECEDORES', true);
insert into departments values ('SEINPLP', 'COPELI', 'SERVIÇO DE INSTRUÇÃO PROCESSUAL', true);
insert into departments values ('EDCON', 'SADCON', 'ESCRITÓRIO SETORIAL DE GESTÃO DA SADCON', true);
insert into departments values ('SAFIN', 'DGER', 'SECRETARIA DE FINANÇAS, ORÇAMENTO E CONTABILIDADE', true);
insert into departments values ('SEGCPA', 'SAFIN', 'SERVIÇO DE GESTÃO', true);
insert into departments values ('COEXECO', 'SAFIN', 'COORDENAÇÃO DE EXECUÇÃO ORÇAMENTÁRIA', true);
insert into departments values ('SERCOE', 'COEXECO', 'SERVIÇO DE REVISÃO E CONTROLE DE EMPENHOS', true);
insert into departments values ('COEXEFI', 'SAFIN', 'COORDENAÇÃO DE EXECUÇÃO FINANCEIRA', true);
insert into departments values ('SEPADA', 'COEXEFI', 'SERVIÇO DE PAGAMENTO DE DESPESAS ADMINISTRATIVAS', true);
insert into departments values ('SEPAF', 'COEXEFI', 'SERVIÇO DE PAGAMENTO A FORNECEDORES', true);
insert into departments values ('SEPAFOL', 'COEXEFI', 'SERVIÇO DE PAGAMENTO DA FOLHA DE PESSOAL', true);
insert into departments values ('CONTAB', 'SAFIN', 'COORDENAÇÃO DE CONTABILIDADE', true);
insert into departments values ('SEACONF', 'CONTAB', 'SERVIÇO DE ANÁLISE DE CONFORMIDADE', true);
insert into departments values ('SECOB', 'CONTAB', 'SERVIÇO DE COBRANÇA ADMINISTRATIVA', true);
insert into departments values ('SECONTA', 'CONTAB', 'SERVIÇO DE CONTABILIDADE ANALÍTICA', true);
insert into departments values ('COPAC', 'SAFIN', 'COORDENAÇÃO DE PLANEJAMENTO E ACOMPANHAMENTO ORÇAMENTÁRIO', true);
insert into departments values ('SEAOIG', 'COPAC', 'SERVIÇO DE ACOMPANHAMENTO ORÇAMENTÁRIO E INFORMAÇÕES GERENCIAIS', true);
insert into departments values ('SEPEO', 'COPAC', 'SERVIÇO DE PLANEJAMENTO E ESTUDOS ORÇAMENTÁRIOS', true);
insert into departments values ('ESAFIN', 'SAFIN', 'ESCRITÓRIO SETORIAL DE GESTÃO DA SAFIN', true);
insert into departments values ('SEGP', 'DGER', 'SECRETARIA DE GESTÃO DE PESSOAS', true);
insert into departments values ('GBSEGP', 'SEGP', 'GABINETE ADMINISTRATIVO DA SEGP', true);
insert into departments values ('NSTSF', 'GBSEGP', 'NÚCLEO DE SERVIDORES EM TRÂNSITO - SF', true);
insert into departments values ('SEACOMP', 'SEGP', 'SERVIÇO DE APOIO A COMISSÕES PROCESSANTES', true);
insert into departments values ('SEARQP', 'SEGP', 'SERVIÇO DE ARQUIVO DE PESSOAL', true);
insert into departments values ('SEATUS', 'SEGP', 'SERVIÇO DE ATENDIMENTO AO USUÁRIO', true);
insert into departments values ('SEPUGP', 'SEGP', 'SERVIÇO DE PUBLICAÇÃO DA SEGP', true);
insert into departments values ('SESTI', 'SEGP', 'SERVIÇO DE SUPORTE EM TECNOLOGIA DA INFORMAÇÃO', true);
insert into departments values ('COAPES', 'SEGP', 'COORDENAÇÃO DE ADMINISTRAÇÃO DE PESSOAL', true);
insert into departments values ('SEAPES', 'COAPES', 'SERVIÇO DE APOIO ADMINISTRATIVO DA COAPES', true);
insert into departments values ('SEDDEV', 'COAPES', 'SERVIÇO DE DIREITOS E DEVERES FUNCIONAIS', true);
insert into departments values ('SEFREQ', 'COAPES', 'SERVIÇO DE CONTROLE DE FREQUÊNCIA', true);
insert into departments values ('SEPCOM', 'COAPES', 'SERVIÇO DE CADASTRO PARLAMENTAR E PESSOAL COMISSIONADO', true);
insert into departments values ('SERCOPE', 'COAPES', 'SERVIÇO DE REGISTRO E CONTROLE DE PESSOAL EFETIVO', true);
insert into departments values ('SGEST', 'COAPES', 'SERVIÇO DE GESTÃO DE ESTÁGIOS', true);
insert into departments values ('NSASF', 'COAPES', 'NÚCLEO DE SERVIDORES AFASTADOS - SF', true);
insert into departments values ('COASAS', 'SEGP', 'COORDENAÇÃO DE ATENÇÃO À SAÚDE DO SERVIDOR', true);
insert into departments values ('SEJM', 'COASAS', 'SERVIÇO DE JUNTA MÉDICA', true);
insert into departments values ('SEMEDE', 'COASAS', 'SERVIÇO MÉDICO DE EMERGÊNCIA', true);
insert into departments values ('SESOQVT', 'COASAS', 'SERVIÇO DE SAÚDE OCUPACIONAL E QUALIDADE DE VIDA NO TRABALHO', true);
insert into departments values ('COASIS', 'SEGP', 'COORDENAÇÃO DE AUTORIZAÇÃO DO SIS', true);
insert into departments values ('COATREL', 'SEGP', 'COORDENAÇÃO DE ATENDIMENTO E RELACIONAMENTO', true);
insert into departments values ('SEABEN', 'COATREL', 'SERVIÇO DE ATENDIMENTO A BENEFICIÁRIOS', true);
insert into departments values ('SECRER', 'COATREL', 'SERVIÇO DE CREDENCIAMENTO E RELACIONAMENTO', true);
insert into departments values ('COBEP', 'SEGP', 'COORDENAÇÃO DE BENEFÍCIOS PREVIDENCIÁRIOS', true);
insert into departments values ('SEAPOPE', 'COBEP', 'SERVIÇO DE APOIO OPERACIONAL', true);
insert into departments values ('SEAPOS', 'COBEP', 'SERVIÇO DE APOSENTADORIA DE SERVIDORES', true);
insert into departments values ('SECOPE', 'COBEP', 'SERVIÇO DE CONCESSÃO DE PENSÕES', true);
insert into departments values ('SEINF', 'COBEP', 'SERVIÇO DE INSTRUÇÃO E REGISTROS FUNCIONAIS', true);
insert into departments values ('SEIPRE', 'COBEP', 'SERVIÇO DE CONTROLE E INFORMAÇÕES PREVIDENCIÁRIAS', true);
insert into departments values ('SESPAR', 'COBEP', 'SERVIÇO DE SEGURIDADE PARLAMENTAR', true);
insert into departments values ('COGEFI', 'SEGP', 'COORDENAÇÃO DE GESTÃO FINANCEIRA DO SIS', true);
insert into departments values ('SECOBR', 'COGEFI', 'SERVIÇO DE COBRANÇA', true);
insert into departments values ('SEPASI', 'COGEFI', 'SERVIÇO DE PAGAMENTO', true);
insert into departments values ('COPAG', 'SEGP', 'COORDENAÇÃO DE PAGAMENTO DE PESSOAL', true);
insert into departments values ('SEACFP', 'COPAG', 'SERVIÇO DE ANÁLISE E CONFERÊNCIA DA FOLHA DE PAGAMENTO', true);
insert into departments values ('SEAPAG', 'COPAG', 'SERVIÇO DE APOIO ADMINISTRATIVO DA COPAG', true);
insert into departments values ('SECOCR', 'COPAG', 'SERVIÇO DE CONSTITUIÇÃO E COBRANÇA DE CRÉDITOS REMUNERATÓRIOS', true);
insert into departments values ('SECONF', 'COPAG', 'SERVIÇO DE CONSIGNAÇÕES FACULTATIVAS', true);
insert into departments values ('SEEFOL', 'COPAG', 'SERVIÇO DE ELABORAÇÃO DE FOLHA', true);
insert into departments values ('SEICAP', 'COPAG', 'SERVIÇO DE INSTRUÇÃO E CÁLCULOS', true);
insert into departments values ('SEOTIS', 'COPAG', 'SERVIÇO DE OBRIGAÇÕES TRIBUTÁRIAS E INFORMAÇÕES SOCIAIS', true);
insert into departments values ('COPOPE', 'SEGP', 'COORDENAÇÃO DE POLÍTICAS DE PESSOAL', true);
insert into departments values ('SECODEPE', 'COPOPE', 'SERVIÇO DE GESTÃO DE COMPETÊNCIAS, DESEMPENHO E POLÍTICAS DE', true);
insert into departments values ('SEGCAS', 'COPOPE', 'SERVIÇO DE GESTÃO DE CARGOS, SALÁRIOS E SELEÇÃO', true);
insert into departments values ('ESEGP', 'SEGP', 'ESCRITÓRIO SETORIAL DE GESTÃO DA SEGP', true);
insert into departments values ('NAPOPD', 'SEGP', 'APOSENTADOS - PD', true);
insert into departments values ('NAPOSE', 'SEGP', 'APOSENTADOS - SEEP', true);
insert into departments values ('NAPOSF', 'SEGP', 'APOSENTADOS - SF', true);
insert into departments values ('NFALPD', 'SEGP', 'FALECIDOS - PD', true);
insert into departments values ('NFALSE', 'SEGP', 'FALECIDOS - SEEP', true);
insert into departments values ('NFALSF', 'SEGP', 'FALECIDOS - SF', true);
insert into departments values ('SEGRAF', 'DGER', 'SECRETARIA DE EDITORAÇÃO E PUBLICAÇÕES', true);
insert into departments values ('GBGRAF', 'SEGRAF', 'GABINETE ADMINISTRATIVO DA SEGRAF', true);
insert into departments values ('SECFAT', 'SEGRAF', 'SERVIÇO DE CONVÊNIOS E FATURAMENTO', true);
insert into departments values ('SEDTI', 'SEGRAF', 'SERVIÇO DE DESENVOLVIMENTO DE TI E ATUALIZAÇÃO TECNOLÓGICA', true);
insert into departments values ('COEDIT', 'SEGRAF', 'COORDENAÇÃO DE EDIÇÕES TÉCNICAS', true);
insert into departments values ('SEAEDI', 'COEDIT', 'SERVIÇO DE APOIO ADMINISTRATIVO', true);
insert into departments values ('SEDACERV', 'COEDIT', 'SERVIÇO DE DISTRIBUIÇÃO E CONTROLE DO ACERVO', true);
insert into departments values ('SELIVR', 'COEDIT', 'SERVIÇO DE LIVRARIA', true);
insert into departments values ('SEMID', 'COEDIT', 'SERVIÇO DE MULTIMÍDIA', true);
insert into departments values ('SEPQS', 'COEDIT', 'SERVIÇO DE PESQUISA DA COEDIT', true);
insert into departments values ('SEPUBT', 'COEDIT', 'SERVIÇO DE PUBLICAÇÕES TÉCNICO LEGISLATIVAS', true);
insert into departments values ('COGEP', 'SEGRAF', 'COORDENAÇÃO DE GESTÃO DA PRODUÇÃO', true);
insert into departments values ('SAUSEP', 'COGEP', 'SERVIÇO DE ATENDIMENTO AO USUÁRIO', true);
insert into departments values ('SEAGEP', 'COGEP', 'SERVIÇO DE APOIO ADMINISTRATIVO', true);
insert into departments values ('SECOQU', 'COGEP', 'SERVIÇO DE CONTROLE DE QUALIDADE', true);
insert into departments values ('SEEREM', 'COGEP', 'SERVIÇO DE EXPEDIÇÃO E REMESSA', true);
insert into departments values ('SEGING', 'COGEP', 'SERVIÇO DE GESTÃO DE INSUMOS GRÁFICOS', true);
insert into departments values ('COIND', 'SEGRAF', 'COORDENAÇÃO INDUSTRIAL', true);
insert into departments values ('SEACAB', 'COIND', 'SERVIÇO DE ACABAMENTO', true);
insert into departments values ('SEACOI', 'COIND', 'SERVIÇO DE APOIO ADMINISTRATIVO', true);
insert into departments values ('SECPRO', 'COIND', 'SERVIÇO DE CONTROLE DA PRODUÇÃO', true);
insert into departments values ('SEFPRO', 'COIND', 'SERVIÇO DE FORMATAÇÃO E PROGRAMAÇÃO VISUAL', true);
insert into departments values ('SEIB', 'COIND', 'SERVIÇO DE IMPRESSÃO EM BRAILLE', true);
insert into departments values ('SEID', 'COIND', 'SERVIÇO DE IMPRESSÃO DIGITAL', true);
insert into departments values ('SEIMOF', 'COIND', 'SERVIÇO DE IMPRESSÃO OFFSET', true);
insert into departments values ('SEMAIN', 'COIND', 'SERVIÇO DE MANUTENÇÃO INDUSTRIAL', true);
insert into departments values ('SEPDIG', 'COIND', 'SERVIÇO DE PROCESSAMENTO DIGITAL', true);
insert into departments values ('SEPIND', 'COIND', 'SERVIÇO DE PROGRAMAÇÃO INDUSTRIAL', true);
insert into departments values ('SEPUBL', 'COIND', 'SERVIÇO DE PUBLICAÇÕES OFICIAIS', true);
insert into departments values ('SERVSO', 'COIND', 'SERVIÇO DE REVISÃO', true);
insert into departments values ('EGRAF', 'SEGRAF', 'ESCRITÓRIO SETORIAL DE GESTÃO DA SEGRAF', true);
insert into departments values ('SGIDOC', 'DGER', 'SECRETARIA DE GESTÃO DE INFORMAÇÃO E DOCUMENTAÇÃO', true);
insert into departments values ('GBSGID', 'SGIDOC', 'GABINETE ADMINISTRATIVO DA SGIDOC', true);
insert into departments values ('SEADAJ', 'SGIDOC', 'SERVIÇO DE APOIO ADMINISTRATIVO', true);
insert into departments values ('SETRIN', 'SGIDOC', 'SERVIÇO DE TRADUÇÃO E INTERPRETAÇÃO', true);
insert into departments values ('SICLAI', 'SGIDOC', 'SERVIÇO DE INFORMAÇÃO AO CIDADÃO', true);
insert into departments values ('COARQ', 'SGIDOC', 'COORDENAÇÃO DE ARQUIVO', true);
insert into departments values ('SEAHIS', 'COARQ', 'SERVIÇO DE ARQUIVO HISTÓRICO', true);
insert into departments values ('SEALEG', 'COARQ', 'SERVIÇO DE ARQUIVO LEGISLATIVO', true);
insert into departments values ('SEARAD', 'COARQ', 'SERVIÇO DE ARQUIVO ADMINISTRATIVO', true);
insert into departments values ('SECPAC', 'COARQ', 'SERVIÇO DE CONSERVAÇÃO E PRESERVAÇÃO DO ACERVO', true);
insert into departments values ('SECTA', 'COARQ', 'SERVIÇO DE CONSULTORIA TÉCNICA ARQUIVÍSTICA', true);
insert into departments values ('SEPESA', 'COARQ', 'SERVIÇO DE PESQUISA E ATENDIMENTO AO USUÁRIO', true);
insert into departments values ('SEPROELE', 'COARQ', 'SERVIÇO DE PROCESSO ELETRÔNICO', true);
insert into departments values ('SEPROT', 'COARQ', 'SERVIÇO DE PROTOCOLO ADMINISTRATIVO', true);
insert into departments values ('SEQARQ', 'COARQ', 'SERVIÇO DE APOIO ADMINISTRATIVO DA COARQ', true);
insert into departments values ('COBIB', 'SGIDOC', 'COORDENAÇÃO DE BIBLIOTECA', true);
insert into departments values ('SEABIB', 'COBIB', 'SERVIÇO DE APOIO ADMINISTRATIVO DA COBIB', true);
insert into departments values ('SEART', 'COBIB', 'SERVIÇO DE PROCESSAMENTO DE ARTIGOS DE REVISTA', true);
insert into departments values ('SEBIBT', 'COBIB', 'SERVIÇO DE BIBLIOTECA TÉCNICA DE INFORMÁTICA', true);
insert into departments values ('SEBID', 'COBIB', 'SERVIÇO DE BIBLIOTECA DIGITAL', true);
insert into departments values ('SEDECO', 'COBIB', 'SERVIÇO DE DESENVOLVIMENTO DE COLEÇÕES', true);
insert into departments values ('SEEMP', 'COBIB', 'SERVIÇO DE EMPRÉSTIMO E DEVOLUÇÃO DE MATERIAL BIBLIOGRÁFICO', true);
insert into departments values ('SEGER', 'COBIB', 'SERVIÇO DE GERÊNCIA DA REDE VIRTUAL DE BIBLIOTECAS', true);
insert into departments values ('SEJOR', 'COBIB', 'SERVIÇO DE PROCESSAMENTO DE JORNAIS', true);
insert into departments values ('SELIV', 'COBIB', 'SERVIÇO DE PROCESSAMENTO DE LIVROS', true);
insert into departments values ('SEMACO', 'COBIB', 'SERVIÇO DE MANUTENÇÃO E CONSERVAÇÃO DO ACERVO', true);
insert into departments values ('SEPESP', 'COBIB', 'SERVIÇO DE PESQUISA PARLAMENTAR', true);
insert into departments values ('SEPRIB', 'COBIB', 'SERVIÇO DE PESQUISA E RECUPERAÇÃO DE INFORMAÇÕES BIBLIOGRÁFICAS', true);
insert into departments values ('SERCOR', 'COBIB', 'SERVIÇO DE REGISTRO DE COLEÇÕES DE REVISTAS', true);
insert into departments values ('COMUS', 'SGIDOC', 'COORDENAÇÃO DE MUSEU', true);
insert into departments values ('SEAAD', 'COMUS', 'SERVIÇO DE APOIO DE ADMINISTRATIVO', true);
insert into departments values ('SEAGEC', 'COMUS', 'SERVIÇO DE ATENDIMENTO E GESTÃO DE ESPAÇOS CULTURAIS', true);
insert into departments values ('SECPM', 'COMUS', 'SERVIÇO DE CONSERVAÇÃO E PRESERVAÇÃO DO MUSEU', true);
insert into departments values ('SEECC', 'COMUS', 'SERVIÇO DE EXPOSIÇÕES, CURADORIA E COMUNICAÇÃO', true);
insert into departments values ('SEGAM', 'COMUS', 'SERVIÇO DE GESTÃO DE ACERVO MUSEOLÓGICO', true);
insert into departments values ('ESGID', 'SGIDOC', 'ESCRITÓRIO SETORIAL DE GESTÃO DA SGIDOC', true);
insert into departments values ('SINFRA', 'DGER', 'SECRETARIA DE INFRAESTRUTURA', true);
insert into departments values ('SEAU', 'SINFRA', 'SERVIÇO DE ATENDIMENTO AO USUÁRIO', true);
insert into departments values ('SEDACOPE', 'SINFRA', 'SERVIÇO DE DIRETRIZES ARQUITETÔNICAS PARA O PATRIMÔNIO EDIFICADO', true);
insert into departments values ('SEORC', 'SINFRA', 'SERVIÇO DE ORÇAMENTOS', true);
insert into departments values ('COEMANT', 'SINFRA', 'COORDENAÇÃO DE ENGENHARIA DE MANUTENÇÃO', true);
insert into departments values ('SEGEEN', 'COEMANT', 'SERVIÇO DE GESTÃO DE ENERGIA ELÉTRICA', true);
insert into departments values ('SEMAC', 'COEMANT', 'SERVIÇO DE MANUTENÇÃO CIVIL', true);
insert into departments values ('SEMAINST', 'COEMANT', 'SERVIÇO DE MANUTENÇÃO DE INSTALAÇÕES', true);
insert into departments values ('SEMEL', 'COEMANT', 'SERVIÇO DE MANUTENÇÃO ELETROMECÂNICA', true);
insert into departments values ('SEPLAG', 'COEMANT', 'SERVIÇO DE PLANEJAMENTO E GESTÃO', true);
insert into departments values ('COPRE', 'SINFRA', 'COORDENAÇÃO DE PROJETOS E REFORMAS', true);
insert into departments values ('SEFIS', 'COPRE', 'SERVIÇO DE FISCALIZAÇÃO', true);
insert into departments values ('SEPINF', 'COPRE', 'SERVIÇO DE PROJETOS DE INFRAESTRUTURA', true);
insert into departments values ('SEPROARQ', 'COPRE', 'SERVIÇO DE PROJETOS DE ARQUITETURA', true);
insert into departments values ('COPROJ', 'SINFRA', 'COORDENAÇÃO DE PROJETOS E OBRAS DE INFRAESTRUTURA', true);
insert into departments values ('EINFRA', 'SINFRA', 'ESCRITÓRIO SETORIAL DE GESTÃO DA SINFRA', true);
insert into departments values ('SPATR', 'DGER', 'SECRETARIA DE PATRIMÔNIO', true);
insert into departments values ('GBPATR', 'SPATR', 'GABINETE ADMINISTRATIVO DA SPATR', true);
insert into departments values ('SEAIM', 'SPATR', 'SERVIÇO DE DOCUMENTAÇÃO E ADMINISTRAÇÃO DE IMÓVEIS', true);
insert into departments values ('SECQEC', 'SPATR', 'SERVIÇO DE CONTROLE DE QUALIDADE E ESPECIFICAÇÕES DE MATERIAIS E BENS COMUNS', true);
insert into departments values ('SECQEE', 'SPATR', 'SERVIÇO DE CONTROLE DE QUALIDADE E ESPECIFICAÇÕES DE MATERIAIS E BENS ESPECIAIS', true);
insert into departments values ('COAPAT', 'SPATR', 'COORDENAÇÃO DE ADMINISTRAÇÃO PATRIMONIAL', true);
insert into departments values ('SEAPAT', 'COAPAT', 'SERVIÇO DE APOIO ADMINISTRATIVO DA COAPAT', true);
insert into departments values ('SEINV', 'COAPAT', 'SERVIÇO DE INVENTÁRIOS', true);
insert into departments values ('SESIN', 'COAPAT', 'SERVIÇO DE SINALIZAÇÃO', true);
insert into departments values ('SETTP', 'COAPAT', 'SERVIÇO DE TOMBAMENTO E DE TRANSFERÊNCIAS PATRIMONIAIS', true);
insert into departments values ('COARO', 'SPATR', 'COORDENAÇÃO DE ADMINISTRAÇÃO DE RESIDÊNCIAS OFICIAIS', true);
insert into departments values ('SECMAN', 'COARO', 'SERVIÇO DE CONSERVAÇÃO E MANUTENÇÃO', true);
insert into departments values ('SEODIU', 'COARO', 'SERVIÇO DE APOIO OPERACIONAL DIURNO', true);
insert into departments values ('SEONOT', 'COARO', 'SERVIÇO DE APOIO OPERACIONAL NOTURNO', true);
insert into departments values ('COASAL', 'SPATR', 'COORDENAÇÃO DE ADMINISTRAÇÃO E SUPRIMENTO DE ALMOXARIFADOS', true);
insert into departments values ('SAINF', 'COASAL', 'SERVIÇO DE ALMOXARIFADO DE INFORMÁTICA', true);
insert into departments values ('SAPF', 'COASAL', 'SERVIÇO DE ALMOXARIFADO DE PRODUTOS GRÁFICOS', true);
insert into departments values ('SEALMX', 'COASAL', 'SERVIÇO DE ADMINISTRAÇÃO DE ALMOXARIFADOS', true);
insert into departments values ('SEASAL', 'COASAL', 'SERVIÇO DE APOIO ADMINISTRATIVO DA COASAL', true);
insert into departments values ('SEPLSU', 'COASAL', 'SERVIÇO DE PLANEJAMENTO E SUPRIMENTO DE BENS DE ALMOXARIFADOS', true);
insert into departments values ('COGER', 'SPATR', 'COORDENAÇÃO DE SERVIÇOS GERAIS', true);
insert into departments values ('SEAOP', 'COGER', 'SERVIÇO DE ATENDIMENTO OPERACIONAL', true);
insert into departments values ('SECOLI', 'COGER', 'SERVIÇO DE CONSERVAÇÃO E LIMPEZA', true);
insert into departments values ('SEPOZE', 'COGER', 'SERVIÇO DE PORTARIA E ZELADORIA', true);
insert into departments values ('SETRAN', 'COGER', 'SERVIÇO DE TRANSPORTES', true);
insert into departments values ('COOTELE', 'SPATR', 'COORDENAÇÃO DE TELECOMUNICAÇÕES', true);
insert into departments values ('SEALMAT', 'COOTELE', 'SERVIÇO DE ALMOXARIFADO DE MATERIAL DE TELECOMUNICAÇÕES', true);
insert into departments values ('SECACD', 'COOTELE', 'SERVIÇO CENTRAL DE ATENDIMENTO E CONTROLE DE DADOS TÉCNICOS', true);
insert into departments values ('SECOMUT', 'COOTELE', 'SERVIÇO DE COMUTAÇÃO TELEFÔNICA', true);
insert into departments values ('SEQUALI', 'COOTELE', 'SERVIÇO DE APOIO ADMINISTRATIVO E CONTROLE DE QUALIDADE', true);
insert into departments values ('SERETE', 'COOTELE', 'SERVIÇO DE REDE TELEFÔNICA', true);
insert into departments values ('SETARIF', 'COOTELE', 'SERVIÇO DE TARIFAÇÃO', true);
insert into departments values ('SETEMO', 'COOTELE', 'SERVIÇO DE TELECOMUNICAÇÕES MÓVEIS', true);
insert into departments values ('SETIIN', 'COOTELE', 'SERVIÇO DE TECNOLOGIA DA INFORMAÇÃO', true);
insert into departments values ('EPATR', 'SPATR', 'ESCRITÓRIO SETORIAL DE GESTÃO DA SPATR', true);
insert into departments values ('SPOL', 'DGER', 'SECRETARIA DE POLÍCIA DO SENADO FEDERAL', true);
insert into departments values ('GBSPSF', 'SPOL', 'GABINETE ADMINISTRATIVO DA SPOL', true);
insert into departments values ('SECEAA', 'SPOL', 'SERVIÇO CENTRAL DE APOIO ADMINISTRATIVO', true);
insert into departments values ('SECOP', 'SPOL', 'SERVIÇO DE CONTROLE OPERACIONAL', true);
insert into departments values ('SEINTE', 'SPOL', 'SERVIÇO DE INTELIGÊNCIA POLICIAL', true);
insert into departments values ('SEPOLI', 'SPOL', 'SERVIÇO DE POLICIAMENTO', true);
insert into departments values ('SEPREV', 'SPOL', 'SERVIÇO DE PREVENÇÃO DE ACIDENTES E SEGURANÇA DO TRABALHO', true);
insert into departments values ('COPINV', 'SPOL', 'COORDENAÇÃO DE POLÍCIA DE INVESTIGAÇÃO', true);
insert into departments values ('SECART', 'COPINV', 'SERVIÇO CARTORÁRIO', true);
insert into departments values ('SERINV', 'COPINV', 'SERVIÇO DE INVESTIGAÇÕES', true);
insert into departments values ('SESTEC', 'COPINV', 'SERVIÇO DE SUPORTE TÉCNICO', true);
insert into departments values ('COPROT', 'SPOL', 'COORDENAÇÃO DE PROTEÇÃO A AUTORIDADES', true);
insert into departments values ('SEAERE', 'COPROT', 'SERVIÇO DE APOIO AEROPORTUÁRIO', true);
insert into departments values ('SEPDIGN', 'COPROT', 'SERVIÇO DE PROTEÇÃO DE DIGNITÁRIOS', true);
insert into departments values ('SEPPLEC', 'COPROT', 'SERVIÇO DE PROTEÇÃO DE PLENÁRIOS E COMISSÕES', true);
insert into departments values ('SEPPRES', 'COPROT', 'SERVIÇO DE PROTEÇÃO PRESIDENCIAL', true);
insert into departments values ('COSUP', 'SPOL', 'COORDENAÇÃO DE SUPORTE ÀS ATIVIDADES POLICIAIS', true);
insert into departments values ('SECRED', 'COSUP', 'SERVIÇO DE CREDENCIAMENTO', true);
insert into departments values ('SELOG', 'COSUP', 'SERVIÇO DE LOGÍSTICA', true);
insert into departments values ('SESTIN', 'COSUP', 'SERVIÇO DE SUPORTE EM TECNOLOGIA DA INFORMAÇÃO', true);
insert into departments values ('SETRE', 'COSUP', 'SERVIÇO DE TREINAMENTO E PROJETOS', true);
insert into departments values ('ESPSF', 'SPOL', 'ESCRITÓRIO SETORIAL DE GESTÃO DA SPOL', true);
insert into departments values ('DIRECON', 'DGER', 'DIRETORIA-EXECUTIVA DE CONTRATAÇÕES', true);
insert into departments values ('SEINTP', 'DIRECON', 'SERVIÇO DE INSTRUÇÃO PROCESSUAL', true);
insert into departments values ('ASSETEC', 'DIRECON', 'ASSESSORIA TÉCNICA', true);
insert into departments values ('ESGEST', 'DIRECON', 'ESCRITÓRIO SETORIAL DE GESTÃO', true);
insert into departments values ('NGACTI', 'DIRECON', 'NÚCLEO DE GESTÃO E APOIO ÀS CONTRATAÇÕES DE TECNOLOGIA DA INFORMAÇÃO', true);
insert into departments values ('NGCIC', 'DIRECON', 'NÚCLEO DE GESTÃO DE CONTRATOS DE INFRAESTRUTURA E COMUNICAÇÃO', true);
insert into departments values ('NGCOT', 'DIRECON', 'NÚCLEO DE GESTÃO DE CONTRATOS DE TERCEIRIZAÇÃO', true);
insert into departments values ('SEAGCO', 'NGCOT', 'SERVIÇO DE APOIO ADMINISTRATIVO DA NGCOT', true);
insert into departments values ('DIREG', 'DGER', 'DIRETORIA-EXECUTIVA DE GESTÃO', true);
insert into departments values ('ATEC', 'DIREG', 'ASSESSORIA TÉCNICA', true);
insert into departments values ('ESEG', 'DIREG', 'ESCRITÓRIO SETORIAL DE GESTÃO', true);
insert into departments values ('NCAS', 'DIREG', 'NÚCLEO DE COORDENAÇÃO DE AÇÕES SOCIOAMBIENTAIS', true);
insert into departments values ('EGOV', 'DGER', 'ESCRITÓRIO CORPORATIVO DE GOVERNANÇA E GESTÃO ESTRATÉGICA', true);
insert into departments values ('SGM', 'OSE', 'SECRETARIA GERAL DA MESA', true);
insert into departments values ('GBSGME', 'SGM', 'GABINETE DA SECRETARIA GERAL DA MESA', true);
insert into departments values ('ATRSGM', 'SGM', 'ASSESSORIA TÉCNICA', true);
insert into departments values ('SAOP', 'SGM', 'SECRETARIA DE APOIO A ÓRGÃOS DO PARLAMENTO', true);
insert into departments values ('GBSAOP', 'SAOP', 'GABINETE ADMINISTRATIVO DA SAOP', true);
insert into departments values ('COAPOP', 'SAOP', 'COORDENAÇÃO DE APOIO A ÓRGÃOS DE PREMIAÇÕES', true);
insert into departments values ('SAPREMI', 'COAPOP', 'SERVIÇO DE APOIO A PREMIAÇÕES', true);
insert into departments values ('COAPOT', 'SAOP', 'COORDENAÇÃO DE APOIO A ÓRGÃOS TÉCNICOS', true);
insert into departments values ('SACCS', 'COAPOT', 'SERVIÇO DE APOIO AO CONSELHO DE COMUNICAÇÃO SOCIAL DO CONGRESSO NACIONAL', true);
insert into departments values ('SCOM', 'SGM', 'SECRETARIA DE COMISSÕES', true);
insert into departments values ('GBSCOM', 'SCOM', 'GABINETE ADMINISTRATIVO DA SECRETARIA DE COMISSÕES', true);
insert into departments values ('SEACOM', 'SCOM', 'SERVIÇO DE APOIO OPERACIONAL ÀS COMISSÕES', true);
insert into departments values ('COAPEC', 'SCOM', 'COORDENAÇÃO DE APOIO AO PROGRAMA E-CIDADANIA', true);
insert into departments values ('COCETI', 'SCOM', 'COORDENAÇÃO DE COMISSÕES ESPECIAIS, TEMPORÁRIAS E PARLAMENTARES DE INQUÉRITO', true);
insert into departments values ('COCM', 'SCOM', 'COORDENAÇÃO DE COMISSÕES MISTAS', true);
insert into departments values ('SACCAI', 'COCM', 'SECRETARIA DE APOIO À COMISSÃO MISTA DE CONTROLE DAS ATIVIDADES DE INTELIGÊNCIA', true);
insert into departments values ('SACMCF', 'COCM', 'SECRETARIA DE APOIO À COMISSÃO MISTA PERMANENTE DE REGULAMENTAÇÃO E CONSOLIDAÇÃO DA LEGISLAÇÃO FEDERAL', true);
insert into departments values ('SACMCPLP', 'COCM', 'SECRETARIA DE APOIO À COMISSÃO MISTA PERMANENTE DE ASSUNTOS', true);
insert into departments values ('SACMCVM', 'COCM', 'SECRETARIA DE APOIO À COMISSÃO MISTA PERMANENTE DE COMBATE À', true);
insert into departments values ('SACMMC', 'COCM', 'SECRETARIA DE APOIO À COMISSÃO MISTA PERMANENTE SOBRE MUDANÇAS', true);
insert into departments values ('COCPSF', 'SCOM', 'COORDENAÇÃO DE COMISSÕES PERMANENTES DO SENADO FEDERAL', true);
insert into departments values ('SACAE', 'COCPSF', 'SECRETARIA DE APOIO À COMISSÃO DE ASSUNTOS ECONÔMICOS', true);
insert into departments values ('SACAS', 'COCPSF', 'SECRETARIA DE APOIO À COMISSÃO DE ASSUNTOS SOCIAIS', true);
insert into departments values ('SACCJ', 'COCPSF', 'SECRETARIA DE APOIO À COMISSÃO DE CONSTITUIÇÃO, JUSTIÇA E CIDADANIA', true);
insert into departments values ('SACCT', 'COCPSF', 'SECRETARIA DE APOIO À COMISSÃO DE CIÊNCIA, TECNOLOGIA, INOVAÇÃO,', true);
insert into departments values ('SACDH', 'COCPSF', 'SECRETARIA DE APOIO À COMISSÃO DE DIREITOS HUMANOS E LEGISLAÇÃO', true);
insert into departments values ('SACDIR', 'COCPSF', 'SECRETARIA DE APOIO À COMISSÃO DIRETORA', true);
insert into departments values ('SACDR', 'COCPSF', 'SECRETARIA DE APOIO À COMISSÃO DE DESENVOLVIMENTO REGIONAL E TURISMO', true);
insert into departments values ('SACE', 'COCPSF', 'SECRETARIA DE APOIO À COMISSÃO DE EDUCAÇÃO, CULTURA E ESPORTE', true);
insert into departments values ('SACIFR', 'COCPSF', 'SECRETARIA DE APOIO À COMISSÃO DE SERVIÇOS DE INFRAESTRUTURA', true);
insert into departments values ('SACMA', 'COCPSF', 'SECRETARIA DE APOIO À COMISSÃO DE MEIO AMBIENTE', true);
insert into departments values ('SACRA', 'COCPSF', 'SECRETARIA DE APOIO À COMISSÃO DE AGRICULTURA E REFORMA AGRÁRIA', true);
insert into departments values ('SACRE', 'COCPSF', 'SECRETARIA DE APOIO À COMISSÃO DE RELAÇÕES EXTERIORES E DEFESA NACIONAL', true);
insert into departments values ('SACTFC', 'COCPSF', 'SECRETARIA DE APOIO À COMISSÃO DE TRANSPARÊNCIA, GOVERNANÇA,', true);
insert into departments values ('SAPCSF', 'COCPSF', 'SECRETARIA DE APOIO À COMISSÃO SENADO DO FUTURO', true);
insert into departments values ('SEADI', 'SGM', 'SECRETARIA DE ATAS E DIÁRIOS', true);
insert into departments values ('GBSEADI', 'SEADI', 'GABINETE ADMINISTRATIVO DA SEADI', true);
insert into departments values ('COELDI', 'SEADI', 'COORDENAÇÃO DE ELABORAÇÃO DE DIÁRIOS', true);
insert into departments values ('SEELAD', 'COELDI', 'SERVIÇO DE ELABORAÇÃO DE DIÁRIOS', true);
insert into departments values ('SERSAD', 'COELDI', 'SERVIÇO DE REVISÃO DE SUMÁRIOS, ATAS E DIÁRIOS', true);
insert into departments values ('SESUMA', 'COELDI', 'SERVIÇO DE ELABORAÇÃO DE SUMÁRIOS E ATAS', true);
insert into departments values ('CORTEL', 'SEADI', 'COORDENAÇÃO DE REGISTROS E TEXTOS LEGISLATIVOS DE PLENÁRIOS', true);
insert into departments values ('SEPTEX', 'CORTEL', 'SERVIÇO DE PROCESSAMENTO DE TEXTOS LEGISLATIVOS', true);
insert into departments values ('SERLEP', 'CORTEL', 'SERVIÇO DE REGISTROS LEGISLATIVOS DE PLENÁRIOS', true);
insert into departments values ('SERTEP', 'CORTEL', 'SERVIÇO DE REVISÃO DE REGISTROS E TEXTOS LEGISLATIVOS DE PLENÁRIOS', true);
insert into departments values ('SERERP', 'SGM', 'SECRETARIA DE REGISTRO E REDAÇÃO PARLAMENTAR', true);
insert into departments values ('GBSERERP', 'SERERP', 'GABINETE ADMINISTRATIVO DA SERERP', true);
insert into departments values ('SEOPE', 'SERERP', 'SERVIÇO DE APOIO OPERACIONAL', true);
insert into departments values ('SETAUD', 'SERERP', 'SERVIÇO DE TÉCNICA DE ÁUDIO', true);
insert into departments values ('CORCOM', 'SERERP', 'COORDENAÇÃO DE REGISTRO EM COMISSÕES', true);
insert into departments values ('SEACO', 'CORCOM', 'SERVIÇO DE APOIO ÀS ATIVIDADES EM COMISSÕES', true);
insert into departments values ('SERCOMIS', 'CORCOM', 'SERVIÇO DE REGISTRO EM COMISSÕES', true);
insert into departments values ('SESUCOM', 'CORCOM', 'SERVIÇO DE SUPERVISÃO DO REGISTRO EM COMISSÕES', true);
insert into departments values ('COREM', 'SERERP', 'COORDENAÇÃO DE REDAÇÃO E MONTAGEM', true);
insert into departments values ('SEREDA', 'COREM', 'SERVIÇO DE REDAÇÃO', true);
insert into departments values ('SERMON', 'COREM', 'SERVIÇO DE MONTAGEM', true);
insert into departments values ('CORER', 'SERERP', 'COORDENAÇÃO DE REVISÃO DE REGISTRO', true);
insert into departments values ('SERER', 'CORER', 'SERVIÇO DE REVISÃO DE REGISTRO', true);
insert into departments values ('CORPLEN', 'SERERP', 'COORDENAÇÃO DE REGISTRO EM PLENÁRIO', true);
insert into departments values ('SERPLEN', 'CORPLEN', 'SERVIÇO DE REGISTRO EM PLENÁRIO', true);
insert into departments values ('SEXPE', 'SGM', 'SECRETARIA DE EXPEDIENTE', true);
insert into departments values ('GBSEXP', 'SEXPE', 'GABINETE ADMINISTRATIVO DA SEXPE', true);
insert into departments values ('COEMAT', 'SEXPE', 'COORDENAÇÃO DE EXPEDIÇÃO E ACOMPANHAMENTO DE MATÉRIAS LEGISLATIVAS', true);
insert into departments values ('SEAMAT', 'COEMAT', 'SERVIÇO DE ACOMPANHAMENTO DE MATÉRIAS LEGISLATIVAS', true);
insert into departments values ('SEEXPED', 'COEMAT', 'SERVIÇO DE EXPEDIÇÃO', true);
insert into departments values ('COEXPO', 'SEXPE', 'COORDENAÇÃO DE ELABORAÇÃO DE EXPEDIENTES OFICIAIS', true);
insert into departments values ('SEDOCE', 'COEXPO', 'SERVIÇO DE DOCUMENTAÇÃO ELETRÔNICA', true);
insert into departments values ('SEINPL', 'COEXPO', 'SERVIÇO DE INSPEÇÃO DOS PROCESSADOS LEGISLATIVOS', true);
insert into departments values ('SINFLEG', 'SGM', 'SECRETARIA DE INFORMAÇÃO LEGISLATIVA', true);
insert into departments values ('SEAIL', 'SINFLEG', 'SERVIÇO DE APOIO ADMINISTRATIVO', true);
insert into departments values ('COER', 'SINFLEG', 'COORDENAÇÃO DE ESTATÍSTICAS, PESQUISA E RELATÓRIOS LEGISLATIVOS', true);
insert into departments values ('SEPEL', 'COER', 'SERVIÇO DE PESQUISA LEGISLATIVA', true);
insert into departments values ('SERAP', 'COER', 'SERVIÇO DO RELATÓRIO DA PRESIDÊNCIA', true);
insert into departments values ('SEREL', 'COER', 'SERVIÇO DE RELATÓRIOS MENSAIS E ESTATÍSTICAS LEGISLATIVAS', true);
insert into departments values ('COPIL', 'SINFLEG', 'COORDENAÇÃO DE PADRONIZAÇÃO DA INFORMAÇÃO LEGISLATIVA', true);
insert into departments values ('SEDAN', 'COPIL', 'SERVIÇO DE ANAIS', true);
insert into departments values ('SEPRON', 'COPIL', 'SERVIÇO DE TRATAMENTO DE PRONUNCIAMENTOS', true);
insert into departments values ('SESINO', 'COPIL', 'SERVIÇO DE SINOPSE', true);
insert into departments values ('NMIL', 'SINFLEG', 'NÚCLEO DE MODERNIZAÇÃO DA INFORMAÇÃO LEGISLATIVA', true);
insert into departments values ('SEGEPROL', 'NMIL', 'SERVIÇO DE GESTÃO DE PROCESSOS LEGISLATIVOS', true);
insert into departments values ('SEMOP', 'NMIL', 'SERVIÇO DE MODERNIZAÇÃO E PROJETOS', true);
insert into departments values ('SLCN', 'SGM', 'SECRETARIA LEGISLATIVA DO CONGRESSO NACIONAL', true);
insert into departments values ('GBADM', 'SLCN', 'GABINETE ADMINISTRATIVO', true);
insert into departments values ('COLECN', 'SLCN', 'COORDENAÇÃO DAS MATÉRIAS LEGISLATIVAS DO CONGRESSO NACIONAL', true);
insert into departments values ('SECOLEG', 'COLECN', 'SERVIÇO DE COLEGIADOS', true);
insert into departments values ('SEMORC', 'COLECN', 'SERVIÇO DE MATÉRIAS ORÇAMENTÁRIAS', true);
insert into departments values ('CORDIACN', 'SLCN', 'COORDENAÇÃO DA ORDEM DO DIA DO CONGRESSO NACIONAL', true);
insert into departments values ('SEMEPRO', 'CORDIACN', 'SERVIÇO DE MEDIDAS PROVISÓRIAS', true);
insert into departments values ('SEVETOS', 'CORDIACN', 'SERVIÇO DE VETOS', true);
insert into departments values ('SLSF', 'SGM', 'SECRETARIA LEGISLATIVA DO SENADO FEDERAL', true);
insert into departments values ('GBLSF', 'SLSF', 'GABINETE ADMINISTRATIVO', true);
insert into departments values ('COINTEL', 'SLSF', 'COORDENAÇÃO DE INTELIGÊNCIA LEGISLATIVA', true);
insert into departments values ('SEAPIL', 'COINTEL', 'SERVIÇO DE ANÁLISE E PRODUÇÃO DE INFORMAÇÕES LEGISLATIVAS', true);
insert into departments values ('COMIL', 'SLSF', 'COORDENAÇÃO DE MATÉRIAS E INSTRUÇÃO LEGISLATIVA', true);
insert into departments values ('SEINLEG', 'COMIL', 'SERVIÇO DE INSTRUÇÃO LEGISLATIVA', true);
insert into departments values ('SEPME', 'COMIL', 'SERVIÇO DE PREPARAÇÃO DE MATÉRIAS E EXPEDIENTES', true);
insert into departments values ('COORD', 'SLSF', 'COORDENAÇÃO DA ORDEM DO DIA', true);
insert into departments values ('SEAPLER', 'COORD', 'SERVIÇO DE ACOMPANHAMENTO DE PLENÁRIO E REVISÃO', true);
insert into departments values ('SEPORD', 'COORD', 'SERVIÇO DE PREPARAÇÃO DA ORDEM DO DIA', true);
insert into departments values ('COALSGM', 'SGM', 'COORDENAÇÃO DE APOIO LOGÍSTICO', true);
insert into departments values ('SEAPA', 'COALSGM', 'SERVIÇO DE APOIO ADMINISTRATIVO', true);
insert into departments values ('SEAPLEN', 'COALSGM', 'SERVIÇO DE APOIO AO PLENÁRIO', true);
insert into departments values ('COAME', 'SGM', 'COORDENAÇÃO DE APOIO À MESA', true);
insert into departments values ('CORELE', 'SGM', 'COORDENAÇÃO DE REDAÇÃO LEGISLATIVA', true);
insert into departments values ('COVESP', 'SGM', 'COORDENAÇÃO DOS SISTEMAS DE VOTAÇÕES ELETRÔNICAS E DE SONORIZAÇÃO DE PLENÁRIOS', true);
insert into departments values ('SEAP', 'COVESP', 'SERVIÇO DE OPERAÇÃO DE ÁUDIO DE PLENÁRIOS', true);
insert into departments values ('SEMAAP', 'COVESP', 'SERVIÇO DE MANUTENÇÃO E ATENDIMENTO AUDIOVISUAL DE PLENÁRIOS', true);
insert into departments values ('SESVE', 'COVESP', 'SERVIÇO DE OPERAÇÃO DO SISTEMA DE VOTAÇÕES ELETRÔNICAS', true);
insert into departments values ('ESGM', 'SGM', 'ESCRITÓRIO SETORIAL DE GESTÃO DA SGM', true);
insert into departments values ('OAS', 'SF', 'ÓRGÃOS DE ASSESSORAMENTO SUPERIOR', true);
insert into departments values ('CONLEG', 'OAS', 'CONSULTORIA LEGISLATIVA', true);
insert into departments values ('GBCLEG', 'CONLEG', 'GABINETE ADMINISTRATIVO DA CONLEG', true);
insert into departments values ('CONTEC', 'CONLEG', 'CONSELHO TÉCNICO DA CONLEG', true);
insert into departments values ('ECOLEG', 'CONLEG', 'ESCRITÓRIO SETORIAL DE GESTÃO DA CONLEG', true);
insert into departments values ('NALEG', 'CONLEG', 'NÚCLEO DE ACOMPANHAMENTO LEGISLATIVO', true);
insert into departments values ('NDIR', 'CONLEG', 'NÚCLEO DE DIREITO', true);
insert into departments values ('NDISC', 'CONLEG', 'NÚCLEO DE DISCURSOS', true);
insert into departments values ('NECO', 'CONLEG', 'NÚCLEO DE ECONOMIA', true);
insert into departments values ('NEPLEG', 'CONLEG', 'NÚCLEO DE ESTUDOS E PESQUISAS DA CONSULTORIA LEGISLATIVA', true);
insert into departments values ('NSOC', 'CONLEG', 'NÚCLEO SOCIAL', true);
insert into departments values ('NSTLEG', 'CONLEG', 'NÚCLEO DE SUPORTE TÉCNICO-LEGISLATIVO', true);
insert into departments values ('SEAPG', 'NSTLEG', 'SERVIÇO DE APOIO GERENCIAL', true);
insert into departments values ('SEATCN', 'NSTLEG', 'SERVIÇO DE APOIO TÉCNICO DA CONLEG', true);
insert into departments values ('CONORF', 'OAS', 'CONSULTORIA DE ORÇAMENTOS, FISCALIZAÇÃO E CONTROLE', true);
insert into departments values ('GBCORF', 'CONORF', 'GABINETE ADMINISTRATIVO DA CONORF', true);
insert into departments values ('ECONOR', 'CONORF', 'ESCRITÓRIO SETORIAL DE GESTÃO DA CONORF', true);
insert into departments values ('NGIOS', 'CONORF', 'NÚCLEO DE SUPORTE TÉCNICO, GESTÃO DA INFORMAÇÃO ORÇAMENTÁRIA E SIGA-BRASIL', true);
insert into departments values ('SEEORÇ', 'NGIOS', 'SERVIÇO DE PESQUISA E ACOMPANHAMENTO DA EXECUÇÃO ORÇAMENTÁRIA', true);
insert into departments values ('SEPROR', 'NGIOS', 'SERVIÇO DE APOIO AO PROCESSO ORÇAMENTÁRIO', true);
insert into departments values ('SESORÇ', 'NGIOS', 'SERVIÇO DE GESTÃO DOS SISTEMAS ORÇAMENTÁRIOS', true);
insert into departments values ('NUCI', 'CONORF', 'NÚCLEO DE EDUCAÇÃO, CULTURA, CIÊNCIA, TECNOLOGIA, INTEGRAÇÃO NACIONAL E MEIO AMBIENTE', true);
insert into departments values ('NUCII', 'CONORF', 'NÚCLEO DE INFRA-ESTRUTURA, PLANEJAMENTO E DESENVOLVIMENTO URBANO', true);
insert into departments values ('NUCIII', 'CONORF', 'NÚCLEO DE FAZENDA E DESENVOLVIMENTO, AGRICULTURA E DESENVOLVIMENTO AGRÁRIO', true);
insert into departments values ('NUCIV', 'CONORF', 'NÚCLEO DE JUSTIÇA E DEFESA, PREVIDÊNCIA E ASSISTÊNCIA SOCIAL', true);
insert into departments values ('NUCV', 'CONORF', 'NÚCLEO DE PODERES DO ESTADO E REPRESENTAÇÃO E SAÚDE', true);
insert into departments values ('ADVOSF', 'OAS', 'ADVOCACIA DO SENADO FEDERAL', true);
insert into departments values ('NASSET', 'ADVOSF', 'NÚCLEO DE ASSESSORAMENTO E ESTUDOS TéCNICOS', true);
insert into departments values ('NATA', 'ADVOSF', 'NÚCLEO DE APOIO TÉCNICO ADMINISTRATIVO', true);
insert into departments values ('SEADV', 'NATA', 'SERVIÇO DE APOIO ADMINISTRATIVO', true);
insert into departments values ('SEEPESQ', 'NATA', 'SERVIÇO DE EXECUÇÃO E PESQUISA', true);
insert into departments values ('EADVOS', 'NATA', 'ESCRITÓRIO SETORIAL DE GESTÃO DA ADVOSF', true);
insert into departments values ('NPADM', 'ADVOSF', 'NÚCLEO DE PROCESSOS ADMINISTRATIVOS', true);
insert into departments values ('NPCONT', 'ADVOSF', 'NÚCLEO DE PROCESSOS DE CONTRATAÇÕES', true);
insert into departments values ('NPJUD', 'ADVOSF', 'NÚCLEO DE PROCESSOS JUDICIAIS', true);
insert into departments values ('AUDIT', 'OAS', 'AUDITORIA DO SENADO FEDERAL', true);
insert into departments values ('GBAUDIT', 'AUDIT', 'GABINETE ADMINISTRATIVO DA AUDIT', true);
insert into departments values ('COAUDCF', 'AUDIT', 'COORDENAÇÃO DE AUDITORIA CONTÁBIL E FINANCEIRA', true);
insert into departments values ('SEAUDCO', 'COAUDCF', 'SERVIÇO DE AUDITORIA CONTÁBIL', true);
insert into departments values ('SEAUDCT', 'COAUDCF', 'SERVIÇO DE AUDITORIA DE CONTAS', true);
insert into departments values ('COAUDCON', 'AUDIT', 'COORDENAÇÃO DE AUDITORIA DE CONTRATAÇÕES', true);
insert into departments values ('SEAUDCOT', 'COAUDCON', 'SERVIÇO DE AUDITORIA DE CONFORMIDADE DE CONTRATAÇÕES', true);
insert into departments values ('SEAUDOPE', 'COAUDCON', 'SERVIÇO DE AUDITORIA OPERACIONAL DE CONTRATAÇÕES', true);
insert into departments values ('COAUDGEP', 'AUDIT', 'COORDENAÇÃO DE AUDITORIA DE GESTÃO DE PESSOAS', true);
insert into departments values ('SEAUDAC', 'COAUDGEP', 'SERVIÇO DE AUDITORIA DE ADMISSÕES E CONCESSÕES', true);
insert into departments values ('SEAUDGEP', 'COAUDGEP', 'SERVIÇO DE AUDITORIA DE GESTÃO DE PESSOAS', true);
insert into departments values ('COAUDTI', 'AUDIT', 'COORDENAÇÃO DE AUDITORIA DE TECNOLOGIA DA INFORMAÇÃO', true);
insert into departments values ('SEAUDGTI', 'COAUDTI', 'SERVIÇO DE AUDITORIA DE GESTÃO DE TECNOLOGIA DA INFORMAÇÃO', true);
insert into departments values ('SEAUDOTI', 'COAUDTI', 'SERVIÇO DE AUDITORIA DE OPERAÇÕES DE TECNOLOGIA DA INFORMAÇÃO', true);
insert into departments values ('ESAUDIT', 'AUDIT', 'ESCRITÓRIO SETORIAL DE GESTÃO DA AUDIT', true);
insert into departments values ('SECOM', 'OAS', 'SECRETARIA DE COMUNICAÇÃO SOCIAL', true);
insert into departments values ('GBECOM', 'SECOM', 'GABINETE ADMINISTRATIVO DA SECOM', true);
insert into departments values ('SEADCO', 'GBECOM', 'SERVIÇO DE APOIO ADMINISTRATIVO DA SECOM', true);
insert into departments values ('ASIMPRE', 'SECOM', 'ASSESSORIA DE IMPRENSA (SECOM)', true);
insert into departments values ('ATCOM', 'SECOM', 'ASSESSORIA TÉCNICA', true);
insert into departments values ('SAJS', 'SECOM', 'SECRETARIA AGÊNCIA E JORNAL DO SENADO', true);
insert into departments values ('SEAAJS', 'SAJS', 'SERVIÇO DE APOIO ADMINISTRATIVO', true);
insert into departments values ('SEARJS', 'SAJS', 'SERVIÇO DE ARTE', true);
insert into departments values ('COBERT', 'SAJS', 'COORDENAÇÃO DE COBERTURA', true);
insert into departments values ('SEAUDIO', 'COBERT', 'SERVIÇO DE AUDIOVISUAL', true);
insert into departments values ('SEFOTO', 'COBERT', 'SERVIÇO DE FOTOGRAFIA', true);
insert into departments values ('SEREPT', 'COBERT', 'SERVIÇO DE REPORTAGEM', true);
insert into departments values ('COEDAJS', 'SAJS', 'COORDENAÇÃO DE EDIÇÃO', true);
insert into departments values ('SEIMPRE', 'COEDAJS', 'SERVIÇO DE IMPRESSOS', true);
insert into departments values ('SEPN', 'COEDAJS', 'SERVIÇO DE PORTAL DE NOTÍCIAS', true);
insert into departments values ('SERCOQ', 'COEDAJS', 'SERVIÇO DE REVISÃO E CONTROLE DE QUALIDADE', true);
insert into departments values ('COJORN', 'SAJS', 'COORDENAÇÃO JORNAL DO SENADO', true);
insert into departments values ('SEC', 'SECOM', 'SECRETARIA DE ENGENHARIA DE COMUNICAÇÃO', true);
insert into departments values ('SAENGC', 'SEC', 'SERVIÇO DE APOIO ADMINISTRATIVO (SEC)', true);
insert into departments values ('CODM', 'SEC', 'COORDENAÇÃO DE DOCUMENTAÇÃO MULTIMÍDIA', true);
insert into departments values ('SEDICO', 'CODM', 'SERVIÇO DE DIFUSÃO DE CONTEÚDO', true);
insert into departments values ('SEIMUL', 'CODM', 'SERVIÇO DE INFRAESTRUTURA E MANUTENÇÃO MULTIMíDIA', true);
insert into departments values ('SESDIG', 'CODM', 'SERVIÇO DE DESENVOLVIMENTO E INTEGRAÇÃO DE SISTEMAS DIGITAIS', true);
insert into departments values ('SETDIG', 'CODM', 'SERVIÇO DE SUPORTE TéCNICO E DIGITALIZAÇÃO', true);
insert into departments values ('COENGTVR', 'SEC', 'COORDENAÇÃO DE ENGENHARIA DE TV E RÁDIO', true);
insert into departments values ('SECONTE', 'COENGTVR', 'SERVIÇO DE CONTROLE DE EQUIPAMENTOS', true);
insert into departments values ('SETETV', 'COENGTVR', 'SERVIÇO TÉCNICO DE TV', true);
insert into departments values ('SETRAD', 'COENGTVR', 'SERVIÇO TÉCNICO DA RÁDIO', true);
insert into departments values ('CORTV', 'SEC', 'COORDENAÇÃO DE TRANSMISSÃO DE TV E RÁDIO', true);
insert into departments values ('SEAMEL', 'CORTV', 'SERVIÇO DE ALMOXARIFADO DE MATERIAL ELETRÔNICO', true);
insert into departments values ('SEATEL', 'CORTV', 'SERVIÇO DE ATENDIMENTO ELETRÔNICO', true);
insert into departments values ('SEMATV', 'CORTV', 'SERVIÇO DE MANUTENÇÃO DA REDE DE TV E RÁDIO', true);
insert into departments values ('SETRAR', 'CORTV', 'SERVIÇO DE TRANSMISSÃO DE RÁDIO', true);
insert into departments values ('SETTV', 'CORTV', 'SERVIÇO DE TRANSMISSÃO DE TV', true);
insert into departments values ('COTI', 'SEC', 'COORDENAÇÃO DE TECNOLOGIA DA INFORMAÇÃO', true);
insert into departments values ('SRPPM', 'SECOM', 'SECRETARIA DE RELAÇÕES PÚBLICAS, PUBLICIDADE E MARKETING', true);
insert into departments values ('SARPSF', 'SRPPM', 'SERVIÇO DE APOIO ADMINISTRATIVO (SRPPM)', true);
insert into departments values ('COGENV', 'SRPPM', 'COORDENAÇÃO DE GESTÃO DE EVENTOS', true);
insert into departments values ('SELEG', 'COGENV', 'SERVIÇO DE EVENTOS LEGISLATIVOS E PROTOCOLARES', true);
insert into departments values ('SEVAD', 'COGENV', 'SERVIÇO DE EVENTOS ADMINISTRATIVOS', true);
insert into departments values ('COMAP', 'SRPPM', 'COORDENAÇÃO DE PUBLICIDADE E MARKETING', true);
insert into departments values ('SEMARK', 'COMAP', 'SERVIÇO DE MARKETING', true);
insert into departments values ('SEPUP', 'COMAP', 'SERVIÇO DE PUBLICIDADE E PROPAGANDA', true);
insert into departments values ('COVISITA', 'SRPPM', 'COORDENAÇÃO DE VISITAÇÃO INSTITUCIONAL E DE RELACIONAMENTO COM A COMUNIDADE', true);
insert into departments values ('SECOI', 'COVISITA', 'SERVIÇO DE COOPERAÇÃO INSTITUCIONAL', true);
insert into departments values ('SEVISI', 'COVISITA', 'SERVIÇO DE VISITA INSTITUCIONAL', true);
insert into departments values ('SRSF', 'SECOM', 'SECRETARIA RÁDIO SENADO', true);
insert into departments values ('SARSF', 'SRSF', 'SERVIÇO DE APOIO ADMINISTRATIVO', true);
insert into departments values ('SEMADI', 'SRSF', 'SERVIÇO DE PROGRAMAÇÃO E DIVULGAÇÃO', true);
insert into departments values ('SERAG', 'SRSF', 'SERVIÇO RÁDIO AGÊNCIA', true);
insert into departments values ('CORED', 'SRSF', 'COORDENAÇÃO DE REDAÇÃO', true);
insert into departments values ('SEPORE', 'CORED', 'SERVIÇO DE PROGRAMAÇÃO REGIONAL', true);
insert into departments values ('SEPROD', 'CORED', 'SERVIÇO DE PRODUÇÃO', true);
insert into departments values ('SEREPO', 'CORED', 'SERVIÇO DE REPORTAGEM', true);
insert into departments values ('SERLOC', 'CORED', 'SERVIÇO DE LOCUÇÃO', true);
insert into departments values ('SEVOZ', 'CORED', 'SERVIÇO DE EDIÇÃO DA VOZ DO BRASIL', true);
insert into departments values ('STVSEN', 'SECOM', 'SECRETARIA TV SENADO', true);
insert into departments values ('COADTV', 'STVSEN', 'COORDENAÇÃO ADMINISTRATIVA', true);
insert into departments values ('SEACER', 'COADTV', 'SERVIÇO DE ACERVO', true);
insert into departments values ('SEOPER', 'COADTV', 'SERVIÇO DE OPERAÇÃO', true);
insert into departments values ('CONTV', 'STVSEN', 'COORDENAÇÃO DE CONTEÚDO', true);
insert into departments values ('SEDCT', 'CONTV', 'SERVIÇO DE DOCUMENTÁRIOS', true);
insert into departments values ('SEPJOR', 'CONTV', 'SERVIÇO DE PROGRAMAS JORNALÍSTICOS', true);
insert into departments values ('SEPRES', 'CONTV', 'SERVIÇO DE PROJETOS ESPECIAIS', true);
insert into departments values ('SERTV', 'CONTV', 'SERVIÇO DE REPORTAGEM DA SECRETARIA TV SENADO', true);
insert into departments values ('COPRTV', 'STVSEN', 'COORDENAÇÃO DE PROGRAMAÇÃO', true);
insert into departments values ('SEINT', 'COPRTV', 'SERVIÇO DE INTERNET', true);
insert into departments values ('SEITPG', 'COPRTV', 'SERVIÇO DE INTERPROGRAMAS', true);
insert into departments values ('SERMPR', 'COPRTV', 'SERVIÇO DE MULTIPROGRAMAÇÃO', true);
insert into departments values ('SEVIIN', 'COPRTV', 'SERVIÇO DE VIVO E ÍNTEGRAS', true);
insert into departments values ('DJORN', 'SECOM', 'DIRETORIA DE JORNALISMO', true);
insert into departments values ('NINTRA', 'DJORN', 'NÚCLEO DE INTRANET', true);
insert into departments values ('NMIDIAS', 'DJORN', 'NÚCLEO DE MÍDIAS SOCIAIS', true);
insert into departments values ('NPAUTAS', 'DJORN', 'NÚCLEO DE PAUTAS INTEGRADAS', true);
insert into departments values ('NCONT', 'SECOM', 'NÚCLEO DE CONTRATAÇÕES E CONTRATOS', true);
insert into departments values ('ESECOM', 'NCONT', 'ESCRITÓRIO SETORIAL DE GESTÃO (SECOM)', true);
insert into departments values ('OSU', 'SF', 'ÓRGÃOS SUPERVISIONADOS', true);
insert into departments values ('ILB', 'OSU', 'INSTITUTO LEGISLATIVO BRASILEIRO', true);
insert into departments values ('DEXILB', 'ILB', 'DIRETORIA EXECUTIVA DO ILB', true);
insert into departments values ('GBILB', 'DEXILB', 'GABINETE ADMINISTRATIVO DA DEXILB', true);
insert into departments values ('SEAT', 'DEXILB', 'SERVIÇO DE APOIO TÉCNICO', true);
insert into departments values ('COADFI', 'DEXILB', 'COORDENAÇÃO ADMINISTRATIVA E FINANCEIRA', true);
insert into departments values ('SCCO', 'COADFI', 'SERVIÇO DE CONTRATOS E CONVÊNIOS', true);
insert into departments values ('SEACOA', 'COADFI', 'SERVIÇO DE APOIO ADMINISTRATIVO DA COADFI', true);
insert into departments values ('SEPLAF', 'COADFI', 'SERVIÇO DE PLANEJAMENTO E ACOMPANHAMENTO FINANCEIRO', true);
insert into departments values ('COESUP', 'DEXILB', 'COORDENAÇÃO DE EDUCAÇÃO SUPERIOR', true);
insert into departments values ('SEFOPEE', 'COESUP', 'SERVIÇO DE FOMENTO À PESQUISA E EXTENSÃO', true);
insert into departments values ('SEPOS', 'COESUP', 'SERVIÇO DOS CURSOS DE PÓS-GRADUAÇÃO', true);
insert into departments values ('SESEA', 'COESUP', 'SERVIÇO DE SECRETARIADO ACADÊMICO', true);
insert into departments values ('COPERI', 'DEXILB', 'COORDENAÇÃO DE PLANEJAMENTO E RELAÇÕES INSTITUCIONAIS', true);
insert into departments values ('SACL', 'COPERI', 'SERVIÇO DE ATENDIMENTO À COMUNIDADE DO LEGISLATIVO', true);
insert into departments values ('SFCO', 'COPERI', 'SERVIÇO DE FORMAÇÃO DA COMUNIDADE', true);
insert into departments values ('SIDV', 'COPERI', 'SERVIÇO DE INFORMAÇÃO E DIVULGAÇÃO', true);
insert into departments values ('SPAC', 'COPERI', 'SERVIÇO DE PLANEJAMENTO E ACOMPANHAMENTO DA COMUNIDADE', true);
insert into departments values ('SPPE', 'COPERI', 'SERVIÇO DE PLANEJAMENTO E PROJETOS ESPECIAIS', true);
insert into departments values ('COTIN', 'DEXILB', 'COORDENAÇÃO DE TECNOLOGIA DA INFORMAÇÃO', true);
insert into departments values ('SEIT', 'COTIN', 'SERVIÇO DE INFRAESTRUTURA TECNOLÓGICA', true);
insert into departments values ('SPDT', 'COTIN', 'SERVIÇO DE PESQUISA E DESENVOLVIMENTO TECNOLÓGICO', true);
insert into departments values ('COTREN', 'DEXILB', 'COORDENAÇÃO DE CAPACITAÇÃO, TREINAMENTO E ENSINO', true);
insert into departments values ('SEED', 'COTREN', 'SERVIÇO DE ENSINO À DISTÂNCIA', true);
insert into departments values ('SETREINA', 'COTREN', 'SERVIÇO DE TREINAMENTO', true);
insert into departments values ('EILB', 'DEXILB', 'ESCRITÓRIO SETORIAL DE GESTÃO DO ILB', true);
insert into departments values ('COCIPE', 'ILB', 'COMITÊ CIENTÍFICO-PEDAGÓGICO', true);
insert into departments values ('COMPER', 'SF', 'COMISSÕES PARLAMENTARES PERMANENTES', true);
insert into departments values ('CAE', 'COMPER', 'COMISSÃO DE ASSUNTOS ECONÔMICOS', true);
insert into departments values ('CAS', 'COMPER', 'COMISSÃO DE ASSUNTOS SOCIAIS', true);
insert into departments values ('CCJ', 'COMPER', 'COMISSÃO DE CONSTITUIÇÃO, JUSTIÇA E CIDADANIA', true);
insert into departments values ('CCT', 'COMPER', 'COMISSÃO DE CIÊNCIA, TECNOLOGIA, INOVAÇÃO, COMUNICAÇÃO E INFORMÁTICA', true);
insert into departments values ('CDH', 'COMPER', 'COMISSÃO DE DIREITOS HUMANOS E LEGISLAÇÃO PARTICIPATIVA', true);
insert into departments values ('CDR', 'COMPER', 'COMISSÃO DE DESENVOLVIMENTO REGIONAL E TURISMO', true);
insert into departments values ('CE', 'COMPER', 'COMISSÃO DE EDUCAÇÃO, CULTURA E ESPORTE', true);
insert into departments values ('CI', 'COMPER', 'COMISSÃO DE SERVIÇOS DE INFRAESTRUTURA', true);
insert into departments values ('CMA', 'COMPER', 'COMISSÃO DE MEIO AMBIENTE', true);
insert into departments values ('CRA', 'COMPER', 'COMISSÃO DE AGRICULTURA E REFORMA AGRÁRIA', true);
insert into departments values ('CRE', 'COMPER', 'COMISSÃO DE RELAÇÕES EXTERIORES', true);
insert into departments values ('CTFC', 'COMPER', 'COMISSÃO DE TRANSPARÊNCIA, GOVERNANÇA, FISCALIZAÇÃO E CONTROLE E DEFESA DO CONSUMIDOR', true);
insert into departments values ('PROPAR', 'SF', 'PROCURADORIA PARLAMENTAR', true);
insert into departments values ('CORREG', 'SF', 'CORREGEDORIA PARLAMENTAR', true);
insert into departments values ('CEDP', 'SF', 'CONSELHO DE ÉTICA E DECORO PARLAMENTAR', true);
insert into departments values ('CCINCL', 'SF', 'CONSELHO DA COMENDA DE INCENTIVO À CULTURA LUÍS DA CÂMARA CASCUDO', true);
insert into departments values ('CCOMESP', 'SF', 'CONSELHO DA COMENDA DO MÉRITO ESPORTIVO', true);
insert into departments values ('CCOMFACF', 'SF', 'CONSELHO DA COMENDA DO MÉRITO FUTEBOLÍSTICO ASSOCIAÇÃO CHAPECOENSE DE FUTEBOL', true);
insert into departments values ('CCOMZA', 'SF', 'CONSELHO DA COMENDA ZILDA ARNS', true);
insert into departments values ('CCONIMS', 'SF', 'CONSELHO DA COMENDA NISE MAGALHÃES DA SILVEIRA', true);
insert into departments values ('CDBL', 'SF', 'CONSELHO DO DIPLOMA BERTHA LUTZ', true);
insert into departments values ('CDGN', 'SF', 'CONSELHO DA COMENDA DORINA DE GOUVÊA NOWILL', true);
insert into departments values ('CDHC', 'SF', 'CONSELHO DA COMENDA DE DIREITOS HUMANOS DOM HÉLDER CÂMARA', true);
insert into departments values ('CEPSF', 'SF', 'CONSELHO DE ESTUDOS POLÍTICOS DO SENADO FEDERAL', true);
insert into departments values ('CPREJE', 'SF', 'CONSELHO DO PRÊMIO JOVEM EMPREENDEDOR', true);
insert into departments values ('CSAN', 'SF', 'CONSELHO DA COMENDA SENADOR ABDIAS NASCIMENTO', true);
insert into departments values ('DJEM', 'SF', 'CONSELHO DO DIPLOMA JOSÉ ERMÍRIO DE MORAES', true);
insert into departments values ('IFI', 'SF', 'INSTITUIÇÃO FISCAL INDEPENDENTE', true);
insert into departments values ('OUVIDSF', 'SF', 'OUVIDORIA DO SENADO FEDERAL', true);
insert into departments values ('CORCID', 'OUVIDSF', 'COORDENAÇÃO DE RELACIONAMENTO COM O CIDADÃO', true);
insert into departments values ('SEALOS', 'CORCID', 'SERVIÇO DE RELACIONAMENTO PÚBLICO ALÔ SENADO', true);
insert into departments values ('SEAPCO', 'CORCID', 'SERVIÇO DE APOIO ADMINISTRATIVO DA CORCID', true);
insert into departments values ('PJRM', 'SF', 'CONSELHO DO PRÊMIO JORNALISTA ROBERTO MARINHO DE MÉRITO JORNALÍSTICO', true);
insert into departments values ('PJS', 'SF', 'CONSELHO DO PROJETO JOVEM SENADOR', true);
insert into departments values ('PMA', 'SF', 'CONSELHO DO PRÊMIO MÉRITO AMBIENTAL', true);
insert into departments values ('PROMUL', 'SF', 'PROCURADORIA ESPECIAL DA MULHER', true);
insert into departments values ('PSFHB', 'SF', 'CONSELHO DO PRÊMIO SENADO FEDERAL DE HISTÓRIA DO BRASIL', true);
insert into departments values ('RPBMER', 'SF', 'REPRESENTAÇÃO BRASILEIRA NO PARLAMENTO DO MERCOSUL', true);
insert into departments values ('CCS', 'SF', 'CONSELHO DE COMUNICAÇÃO SOCIAL', true);
insert into departments values ('COCN', 'SF', 'CONSELHO DA ORDEM DO CONGRESSO NACIONAL', true);
insert into departments values ('CMCF', 'COCN', 'COMISSÃO MISTA PERMANENTE DE REGULAMENTAÇÃO E CONSOLIDAÇÃO DA LEGISLAÇÃO FEDERAL', true);
insert into departments values ('CMCPLP', 'COCN', 'COMISSÃO MISTA DO CONGRESSO NACIONAL DE ASSUNTOS RELACIONADOS À COMUNIDADE DOS PAÍSES DE LÍNGUA PORTUGUESA', true);
insert into departments values ('CMCVM', 'COCN', 'COMISSÃO PERMANENTE MISTA DE COMBATE À VIOLÊNCIA CONTRA A MULHER', true);
insert into departments values ('CMMC', 'COCN', 'COMISSÃO MISTA PERMANENTE SOBRE MUDANÇAS CLIMÁTICAS', true);
insert into departments values ('CMO', 'COCN', 'COMISSÃO MISTA DE PLANOS, ORÇAMENTOS PÚBLICOS E FISCALIZAÇÃO', true);
insert into departments values ('DMEDR', 'SF', 'CONSELHO DO DIPLOMA DO MÉRITO EDUCATIVO DARCY RIBEIRO', true);
insert into departments values ('GLMAICN', 'SF', 'GABINETE DA LIDERANÇA DO BLOCO DA MAIORIA NO CONGRESSO NACIONAL', true);
