ALTER TABLE orders ALTER COLUMN request_department SET NOT NULL;

ALTER TABLE orders ALTER COLUMN completed DROP NOT NULL;
ALTER TABLE orders ALTER COLUMN ans_factor DROP NOT NULL;
ALTER TABLE orders ALTER COLUMN request_local DROP NOT NULL;
ALTER TABLE orders ALTER COLUMN sigad DROP NOT NULL;