-- bypass de RLS ---> SOMENTE PARA ADMINS!
ALTER ROLE role_name WITH BYPASSRLS;

CREATE ROLE unauth;
CREATE ROLE auth;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO unauth;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO auth;

---- tudo:
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO unauth;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO unauth;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO auth;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO unauth;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO auth;