CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE ROLE unauth;
CREATE ROLE auth;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO unauth;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO auth;

ALTER SEQUENCE orders_order_id_seq RESTART WITH 10;
ALTER SEQUENCE persons_person_id_seq RESTART WITH 10;

