const fakeData = [
  {
    event: 'insert',
    time: '2004-10-19',
    personName: 'Pedro Serafim',
    personId: '00001',
    senderName: 'Seplag',
    senderId: '00001',
    recipientName: null,
    recipientId: null,
    taskStatusText: 'Fila de Espera',
    taskStatusId: '001',
    note: 'Tarefa criada com sucesso.',
  },
  {
    event: 'move',
    time: '2004-10-20',
    personName: 'Henrique Zaidan',
    personId: '00002',
    senderName: 'Seplag',
    senderId: '00001',
    recipientName: null,
    recipientId: null,
    taskStatusText: 'Em Análise',
    taskStatusId: '002',
    note: 'Verificar detalhes do projeto que deu início a esta tarefa.',
  },
  {
    event: 'send',
    time: '2004-10-21',
    personName: 'Pedro Serafim',
    personId: '00001',
    senderName: 'Seplag',
    senderId: '00001',
    recipientName: 'RCS Tecnologia - Posto Anexo II',
    recipientId: '00015',
    taskStatusText: null,
    taskStatusId: null,
    note: 'Subistituir os circuítos de tomadas de todas as copas.',
  },
  {
    event: 'receive',
    time: '2004-10-22',
    personName: 'Flávio Antônio',
    personId: '00004',
    senderName: 'RCS Tecnologia - Posto Anexo II',
    senderId: '00015',
    recipientName: null,
    recipientId: null,
    taskStatusText: 'Fila de Espera',
    taskStatusId: '001',
    note: null,
  },
  {
    event: 'move',
    time: '2004-10-23',
    personName: 'Flávio Antônio',
    personId: '00004',
    senderName: 'RCS Tecnologia - Posto Anexo II',
    senderId: '00001',
    recipientName: null,
    recipientId: null,
    taskStatusText: 'Em execução',
    taskStatusId: '005',
    note: 'Início da execução da tarefa.',
  },
  {
    event: 'send',
    time: '2004-10-24',
    personName: 'Flávio Antônio',
    personId: '00004',
    senderName: 'RCS Tecnologia - Posto Anexo II',
    senderId: '00004',
    recipientName: 'Entherm - Posto CM3',
    recipientId: '00005',
    taskStatusText: null,
    taskStatusId: null,
    note: 'Checar todos os dutos de ar-condicionado. Vazamentos foram detectados no local.',
  },
  {
    event: 'receive',
    time: '2004-10-25',
    personName: 'Ricardo Luís',
    personId: '00006',
    senderName: 'Entherm - Posto CM3',
    senderId: '00005',
    recipientName: null,
    recipientId: null,
    taskStatusText: 'Fila de Espera',
    taskStatusId: '001',
    note: null,
  },
  {
    event: 'move',
    time: '2004-10-26',
    personName: 'Ricardo Luís',
    personId: '00008',
    senderName: 'Entherm - Posto CM3',
    senderId: '00005',
    recipientName: null,
    recipientId: null,
    taskStatusText: 'Em análise',
    taskStatusId: '001',
    note: 'Análise de possíveis vazamentos.',
  },
  {
    event: 'send',
    time: '2004-10-27',
    personName: 'Ricardo Luís',
    personId: '00008',
    senderName: 'Entherm - Posto CM3',
    senderId: '00005',
    recipientName: 'Seplag',
    recipientId: '00001',
    taskStatusText: null,
    taskStatusId: null,
    note: 'Posto de serviço sem funcionários para conclusão da tarefa.',
  },
  {
    event: 'cancel',
    time: '2004-10-28',
    personName: 'Ricardo Luís',
    personId: '00006',
    senderName: 'Entherm - Posto CM3',
    senderId: '00005',
    recipientName: null,
    recipientId: null,
    taskStatusText: null,
    taskStatusId: null,
    note: '',
  },
  {
    event: 'move',
    time: '2004-10-29',
    personName: 'Ricardo Luís',
    personId: '00008',
    senderName: 'Entherm - Posto CM3',
    senderId: '00005',
    recipientName: null,
    recipientId: null,
    taskStatusText: 'Em execução',
    taskStatusId: '001',
    note: 'Análise de possíveis vazamentos.',
  },
];

export default fakeData;