export const fakeWorkOrders = {
  items: [
    {
      id: "12345",
      creationDate: "25/06/2019",
      selectedService: "Troca de lâmpada",
      lastUpdate: "26/06/2019",
      reqName: "Henrique Zaidan Lopes",
      reqEmail: "hzlopes@senado.leg.br",
      reqPhone: "(61)33032339",
      conName: "Henrique Zaidan Lopes",
      conEmail: "hzlopes@senado.leg.br",
      conPhone: "(61)33032339",
      directions: "Mezanino SINFRA, sala do SEPLAG",
      description: "Favor trocar a lâmpada da sala.",
      details: "Lâmpada queimou ontem.",
      files: "Nenhum",
      situation: "Pendente",
      priority: "Normal",
      assignedTo: "RCS Tecnologia",
      category: "Elétrica",
      sigad: "N/A",
      requestingDepartment: "SEPLAG",
      messageToRequester: "",
      budget: "",
      initialDate: "25/06/2019",
      finalDate: "30/06/2019",
      progress: "0 %",
      checked: "",
      executor: "Nikola Tesla",
      ans: "",
      multiTask: "",
      relatedWorkOrders: "",
      subTasks: "",
      log: "Atualizado por Henrique Zaidan.",
      status: "Pendente",
      asset: "BL14-MEZ-043",
      local: "BL14-MEZ-043"
    },
  ],
  tableConfig: [
    { name: "ID",     style: { width: "20%" }, className: "text-center", attr: "id" },
    { name: "Status", style: { width: "20%" }, className: "text-center", attr: "status" },
    { name: "Ativo",  style: { width: "20%" }, className: "text-center", attr: "asset" },
    { name: "Local",  style: { width: "20%" }, className: "text-center", attr: "local" },
  ]
};